---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: kuberseni
  sources:
    - repoURL: https://kubernetes-sigs.github.io/external-dns/
      chart: external-dns
      targetRevision: 1.21.1
      helm:
        valueFiles:
          - $values/cluster/apps/external-dns/values.yaml
    - repoURL: https://github.com/Arsenikki/kuberseni-gitops
      targetRevision: feat/talos
      ref: values
    - repoURL: https://github.com/Arsenikki/kuberseni-gitops
      targetRevision: feat/talos
      path: cluster/apps/external-dns
      directory:
        exclude: "{values.yaml,argocd-app.yaml}"
  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
