---
# Cloudflare API token for external-dns
# 1Password item: "kuberseni/cloudflare" with field: api_token
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token
  namespace: external-dns
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: cloudflare-api-token
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: "cloudflare"
        property: api_token
