---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: lazylibrarian
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: lazylibrarian
      version: 7.3.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 1m
  values:
    image:
      repository: ghcr.io/arsenikki/lazylibrarian
      tag: 3e0f3a37-ls66
    env:
      # -- Set the container timezone
      TZ: UTC
      # -- Specify the user ID the application will run as
      PUID: "1001"
      # -- Specify the group ID the application will run as
      PGID: "1001"
    persistence:
      config:
        enabled: true
        existingClaim: lazylibrarian-config
      books:
        enabled: true
        mountPath: /books
        existingClaim: books-pvc
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: OnRootMismatch
