---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: zigbee2mqtt
  namespace: home-automation
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-charts
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: mosquitto
      namespace: home-automation
  values:
    controller:
      type: statefulset
    image:
      repository: ghcr.io/koenkk/zigbee2mqtt
      tag: 1.33.1
    env:
      TZ: Europe/London
      ZIGBEE2MQTT_DATA: /config
    service:
      main:
        ports:
          http:
            port: 80
    ingress:
      main:
        enabled: true
        annotations:
          # Automatically generate TLS certificate
          kubernetes.io/tls-acme: "true"
          # Use forward-auth middleware for authentication
          traefik.ingress.kubernetes.io/router.middlewares: "traefik-forward-auth@kubernetescrd"
        hosts:
          - host: zigbee.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: zigbee2mqtt-tls
            hosts:
             - zigbee.${SECRET_DOMAIN}
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: OnRootMismatch
    volumeClaimTemplates:
      - name: config
        mountPath: /config
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClass: longhorn-fast-replicated
    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        memory: 500Mi