---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: paperless-ngx-app
  namespace: flux-system
spec:
  path: ./apps/paperless-ngx/app
  prune: true
  sourceRef:
    kind: OCIRepository
    name: kuberseni-gitops-source
    namespace: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substitute: {}
    substituteFrom:
    - kind: ConfigMap
      name: cluster-settings
    - kind: Secret
      name: cluster-secrets
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
