---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tailscale
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      chart: tailscale-subnet-router
      version: 1.1.1
      sourceRef:
        kind: HelmRepository
        name: gtaylor-charts
        namespace: flux-system
      interval: 1m
  values:
    image:
      repository: ghcr.io/tailscale/tailscale
      tag: "v1.32.3"
    tailscale:
      auth:
        # -- The name of the secret containing a Tailscale auth key
        secretName: tailscale-subnet-router-secrets
        # -- The key within the above Secret that contains a Tailscale auth key
        secretKey: AUTH_KEY
      state:
        # -- The secret that the subnet router will store its state in
        secretName: tailscale-subnet-router-state
      # -- Routes for the subnet router to publish
      routes:
        - "${NETWORK_LOCAL_CIDR}"
        - "${NETWORK_K8S_SERVICE_CIDR}"
        - "${NETWORK_K8S_CLUSTER_CIDR}"
    securityContext:
      runAsUser: 568
      runAsGroup: 568
