---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      chart: external-dns
      version: 6.34.2
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      registry: k8s.gcr.io
      repository: external-dns/external-dns
      tag: v0.14.0
    logLevel: debug
    domainFilters:
      - "${SECRET_DOMAIN}"
    sources:
      - ingress
    provider: cloudflare
    cloudflare:
      secretName: cloudflare-api-token
      email: "${SECRET_CLOUDFLARE_EMAIL}"
      proxied: false
    policy: sync
    crd:
      # disabled, pulled from source repo in crds/
      create: false
      apiversion: externaldns.k8s.io/v1alpha1
      kind: DNSEndpoint
    annotationFilter: "external-dns/is-public in (true)"
    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        memory: 250Mi
