apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: networking
stringData:
    token: ENC[AES256_GCM,data:qAwmnGH6V8EGVS9SG1FkS0/t7ySPXS88BZJyrRLf+QCvxQP2HaP4AA==,iv:bkItbuF8jCHuQZBof5nTu114DATKtAHB99QRFWz1+QA=,tag:98iaqSvMMLEvxAE6TGspcg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17ax8w6axmjplnnf38t8qlqtz2uj2k685fwnl6uy6u8q2rwsjmd6qa6ddv9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1UmIrb1A4QUd0ZkQxdGhy
            WVIva3VhR2I5OXMvUjQvdGc1K1d5NExlSnlNCkJwWGgxckNGS25WSXJNRHZvMDlm
            MTE0Q2ZoZW5OaW9kS2IzSitQR1lWcWcKLS0tIFNmNmdPUnI5VWhwWFBiZDJqdXgw
            N3pCNXl0ekZ1WUxhT0szSVg2akwzNE0KAE+adtVL1e+x0XTLY12iYMuUwB1NHzSG
            kL7zhCDWkNyR/WW5RpLudPlkUfRG+KIpphvH2VYfPARYgrkaDDeIAQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-16T22:00:42Z"
    mac: ENC[AES256_GCM,data:rYrPLUwYU0KyL7tmgdDI687pAsV7B04gX7PKQKK423oRalAAiUyFdN8SjG7V7+1lmNoi56p1FXrX0fM2bQy3rbmKssDkADF57IR3iCqUihqqkRRxlp9pbDwIp3aXbb0EmQF1FEsX5lfaHoYQo2CyTE3mpx8Yep7q077DpK2r6q0=,iv:vPpCmWxicKl9638sXomtmVFESsDdv6Z+OkMViImd220=,tag:O1KYvtmc8F9Nb7EUOc/faw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
