---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: radarr
  namespace: media
spec:
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-charts
        namespace: flux-system
  interval: 30m
  values:
    image:
      repository: ghcr.io/onedr0p/radarr
      tag: 5.17.2.9580
    env:
      TZ: "Europe/London"
    service:
      main:
        ports:
          http:
            port: 7878
    ingress:
      main:
        enabled: true
        ingressClassName: traefik
        annotations:
          # Automatically generate TLS certificate
          kubernetes.io/tls-acme: "true"
          # Use forward-auth middleware for authentication
          traefik.ingress.kubernetes.io/router.middlewares: "authentik-forward-auth@kubernetescrd"
        hosts:
          - host: radarr.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: radarr-tls
            hosts:
              - radarr.${SECRET_DOMAIN}
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups: [10000]
    persistence:
      config:
        enabled: true
        existingClaim: radarr-config
      media:
        enabled: true
        mountPath: /data
        existingClaim: media-pvc
    resources:
      requests:
        cpu: 100m
        memory: 256M
      limits:
        memory: 1024M
