---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: radarr
  namespace: media
spec:
  chart:
    spec:
      chart: app-template
      version: 1.3.1
      sourceRef:
        kind: HelmRepository
        name: bjw-charts
        namespace: flux-system
  interval: 30m
  values:
    image:
      repository: ghcr.io/onedr0p/radarr-develop
      tag: 4.4.1.6926@sha256:f5ffec33b203f9052caf1cf484b1d30f9dc0bc3268c8a439b45e67c3c4dbe5b2
    env:
      TZ: "Europe/Helsinki"
    service:
      main:
        ports:
          http:
            port: 7878
    ingress:
      main: 
        enabled: true
        annotations:
          # Use forward-auth middleware for authentication
          traefik.ingress.kubernetes.io/router.middlewares: "traefik-forward-auth@kubernetescrd"
          # Let external-dns manage cloudflare DNS records
          external-dns/is-public: "true"
        hosts:
        - host: radarr.${SECRET_DOMAIN}
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - radarr.${SECRET_DOMAIN}
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 65539
    persistence:
      config:
        enabled: true
        existingClaim: radarr-config
      media:
        enabled: true
        mountPath: /data
        existingClaim: media-pvc-01
    resources:
      requests:
        cpu: 100m
        memory: 256M
      limits:
        memory: 1024M