loki:
  image:
    repository: grafana/loki
    tag: 2.9.1
  auth_enabled: false
  storage:
    type: filesystem
  commonConfig:
    replication_factor: 1
  limits_config:
    retention_period: 7d
  rulerConfig:
    alertmanager_url: http://kube-prometheus-stack-alertmanager:9093

write:
  replicas: 0
read:
  replicas: 0
backend:
  replicas: 0

singleBinary:
  replicas: 1
  persistence:
    size: 10Gi
    storageClass: ceph-block

test:
  enabled: false

monitoring:
  selfMonitoring:
    enabled: false
  lokiCanary:
    enabled: false
