---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-config
  namespace: n8n
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn-fast-replicated
