---
# code-server SSH public key for VS Code access to Home Assistant config
# 1Password item: "home-assistant" field: ssh_public_key
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: code-server
  namespace: home-automation
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: code-server
    creationPolicy: Owner
  data:
    - secretKey: id_rsa
      remoteRef:
        key: "home-assistant"
        property: ssh_public_key
