---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: lidarr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: lidarr
      version: 14.0.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/lidarr
      tag: v1.0.0.2255
    env:
      TZ: "Europe/Helsinki"
    ingress:
      main:
        enabled: true
        annotations:
          # Use Traefik for ingress
          kubernetes.io/ingress.class: "traefik"
          # Use authelia-forward-auth middleware for authentication
          traefik.ingress.kubernetes.io/router.middlewares: "security-forwardauth-authelia@kubernetescrd"
          # Use default cluster-issuer
          kubernetes.io/tls-acme: "true"
          # Only allow websecure endpoint
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          # Set to passthrough TLS to backend service
          traefik.ingress.kubernetes.io/router.tls: "true"
        hosts:
          - host: "lidarr.${SECRET_DOMAIN}"
            paths:
              - path: /
        tls:
          - secretName: lidarr-tls
            hosts:
              - "lidarr.${SECRET_DOMAIN}"
    persistence:
      config:
        enabled: true
        existingClaim: lidarr-config
      media:
        enabled: true
        existingClaim: media-pvc
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: OnRootMismatch
    resources:
      requests:
        memory: 150Mi
        cpu: 100m
      limits:
        memory: 500Mi
