---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: media
spec:
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-charts
        namespace: flux-system
  interval: 30m
  values:
    controller:
      type: statefulset
    image:
      repository: ghcr.io/onedr0p/qbittorrent
      tag: 4.6.3
    env:
      TZ: "Europe/London"
      UMASK: "022"
      QBITTORRENT__PORT: 8080
      QBITTORRENT__BT_PORT: 50413
      QBT_BitTorrent__Session__Interface: wg0
      QBT_BitTorrent__Session__InterfaceName: wg0
      QBT_Preferences__WebUI__AuthSubnetWhitelistEnabled: true
      QBT_Preferences__WebUI__AuthSubnetWhitelist: |-
        ${CILIUM_LB_POOL}, ${NETWORK_K8S_SERVICE_CIDR}, ${NETWORK_K8S_CLUSTER_CIDR}
      QBT_Preferences__WebUI__LocalHostAuth: false
      QBT_BitTorrent__Session__DefaultSavePath: "/data/downloads"
    hostname: qbittorrent
    service:
      main:
        ports:
          http:
            port: 8080
      bittorrent:
        enabled: true
        type: ClusterIP
        ports:
          bittorrent:
            enabled: true
            port: 50413
            protocol: TCP
            targetPort: 50413
    addons:
      netshoot:
        enabled: true
      vpn:
        enabled: true
        type: gluetun
        gluetun:
          image:
            repository: ghcr.io/qdm12/gluetun
            tag: v3.35.0@sha256:a98d1ec99e09a1b806aff7f0c3d8a133a8ede7d3d7a250b62029a39a61f01525
        env:
          - name: VPN_SERVICE_PROVIDER
            value: airvpn
          - name: VPN_TYPE
            value: wireguard
          - name: VPN_INTERFACE
            value: wg0
          - name: FIREWALL_INPUT_PORTS
            value: "8080"
            # Allow access to k8s subnets
          - name: FIREWALL_OUTBOUND_SUBNETS
            value: "10.42.0.0/16,10.43.0.0/16"
          - name: DOT
            value: "off"
          - name: SERVER_CITIES
            value: Alblasserdam
          - name: WIREGUARD_ADDRESSES
            value: ${SECRET_WG_ADDRESSES}
          - name: WIREGUARD_PRIVATE_KEY
            value: ${SECRET_WG_PRIVATE_KEY}
          - name: WIREGUARD_PRESHARED_KEY
            value: ${SECRET_WG_PRESHARED_KEY}
          - name: LOG_LEVEL
            value: debug
            # Current VPN provider seems to have issues with health checks,
            # so making them less frequent
          - name: HEALTH_TARGET_ADDRESS
            value: "cloudflare.com:443"
          - name: HEALTH_VPN_DURATION_INITIAL
            value: "20s"
          - name: HEALTH_VPN_DURATION_ADDITION
            value: "1m"
          - name: HEALTH_SUCCESS_WAIT_DURATION
            value: "30m"
        securityContext:
          privileged: true
          capabilities:
            add:
              - NET_ADMIN
              - SYS_MODULE
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false
    ingress:
      main:
        enabled: true
        annotations:
          # Automatically generate TLS certificate
          kubernetes.io/tls-acme: "true"
          # Use forward-auth middleware for authentication
          traefik.ingress.kubernetes.io/router.middlewares: "traefik-forward-auth@kubernetescrd"
          # Let external-dns manage cloudflare DNS records
          external-dns/is-public: "true"
        hosts:
          - host: qbittorrent.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: qbittorrent-tls
            hosts:
              - qbittorrent.${SECRET_DOMAIN}
    persistence:
      config:
        enabled: true
        existingClaim: qbittorrent-config
      media:
        enabled: true
        mountPath: /data
        existingClaim: media-pvc
    securityContext:
      runAsUser: 568
      runAsGroup: 568
    podSecurityContext:
      fsGroup: 568
      fsGroupChangePolicy: OnRootMismatch
    resources:
      requests:
        cpu: 100m
        memory: 128M
      limits:
        memory: 1500M
