---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ser2net-config
  namespace: ser2net
data:
  ser2net.yaml: |
    connection: &con01
    accepter: tcp,20108
    connector: serialdev,/dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20231219170448-if00,115200n81,local,dtr=off,rts=off
    options:
      kickolduser: true
