---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-stag
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: "arsenileskinen@hotmail.com"
    privateKeySecretRef:
      name: letsencrypt-stag
    solvers:
      - dns01:
          cloudflare:
            email: "arsenileskinen@hotmail.com"
            apiTokenSecretRef:
              name: cloudflare-token-secret
              key: cloudflare-token
