csiDriver:
  name: org.democratic-csi.nfs

storageClasses:
  - name: truenas-nfs-csi
    defaultClass: true
    reclaimPolicy: Retain
    volumeBindingMode: Immediate
    allowVolumeExpansion: true
    parameters:
      fsType: nfs
    mountOptions:
      - noatime
      - nfsvers=4

driver:
  config:
    driver: freenas-nfs
    instance_id:
    httpConnection:
      protocol: http
      host: "192.168.1.2"
      port: 80
      # Credentials injected via ESO → democratic-csi-truenas-secret
      username: ""
      password: ""
      allowInsecure: true
    sshConnection:
      host: "192.168.1.2"
      port: 22
      username: ""
      password: ""
    zfs:
      datasetParentName: main/nfs/vols
      detachedSnapshotsDatasetParentName: main/nfs/snaps
      datasetEnableQuotas: true
      datasetEnableReservation: false
      datasetPermissionsMode: "0777"
      datasetPermissionsUser: 0
      datasetPermissionsGroup: 0
    nfs:
      shareHost: "192.168.1.2"
      shareAlldirs: false
      shareAllowedHosts: []
      shareAllowedNetworks: []
      shareMaprootUser: root
      shareMaprootGroup: wheel
      shareMapallUser: ""
      shareMapallGroup: ""
