---
stores:
  yaml:
    indent: 2

creation_rules:
  - path_regex: cluster/*
    age: "age17ax8w6axmjplnnf38t8qlqtz2uj2k685fwnl6uy6u8q2rwsjmd6qa6ddv9"
    encrypted_regex: ^(data|stringData)$

  - path_regex: infra/talos/.*\.yaml
    age: "age17ax8w6axmjplnnf38t8qlqtz2uj2k685fwnl6uy6u8q2rwsjmd6qa6ddv9"
    encrypted_regex: ^(.*secret.*|.*token.*|.*key.*|.*password.*|crt|bootstraptoken|secretboxencryptionsecret)$

  - path_regex: infra/
    age: "age17ax8w6axmjplnnf38t8qlqtz2uj2k685fwnl6uy6u8q2rwsjmd6qa6ddv9"
