authentik:
  # All secret env vars injected from authentik-secrets k8s Secret (created by ExternalSecret).
  # Secret must contain: AUTHENTIK_SECRET_KEY, AUTHENTIK_BOOTSTRAP_TOKEN,
  # AUTHENTIK_BOOTSTRAP_PASSWORD, AUTHENTIK_POSTGRESQL__PASSWORD
  existingSecret:
    secretName: authentik-secrets
  log_level: info

blueprints:
  configMaps:
    - authentik-blueprints

server:
  ingress:
    enabled: true
    hosts:
      - authentik.homelab.arsenikki.casa
    annotations:
      kubernetes.io/tls-acme: "true"
      external-dns/is-public: "true"
    tls:
      - secretName: authentik-tls
        hosts:
          - authentik.homelab.arsenikki.casa

postgresql:
  enabled: true
  auth:
    existingSecret: authentik-secrets
    secretKeys:
      adminPasswordKey: AUTHENTIK_POSTGRES_PASSWORD

redis:
  enabled: true
