---
apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-config
  namespace: media
data:
  # Generic
  IMMICH_SERVER_URL: http://immich-server.media.svc.cluster.local:3001
  DISABLE_REVERSE_GEOCODING: "true"
  ENABLE_MAPBOX: "false"
  LOG_LEVEL: verbose
  NODE_ENV: "production"
  # Redis
  REDIS_HOSTNAME: immich-redis.media.svc.cluster.local
  REDIS_PORT: "6379"
  # Postgres
  DB_HOSTNAME: postgres.cloudnative-pg.svc.cluster.local
  DB_PORT: "5432"
