---
apiVersion: v1
kind: Service
metadata:
  name: media-notifier
  namespace: media
  labels:
    app: media-notifier
spec:
  selector:
    app: media-notifier
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
