---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authelia-redis-data
  namespace: security
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn-fast-replicated
