---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: democratic-csi
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: kuberseni
  sources:
    - repoURL: https://democratic-csi.github.io/charts
      chart: democratic-csi
      targetRevision: 0.14.5
      helm:
        valueFiles:
          - $values/cluster/core/democratic-csi/values.yaml
    - repoURL: https://github.com/Arsenikki/kuberseni-gitops
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: democratic-csi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
