---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: intel-gpu-plugin
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: kuberseni
  sources:
    - repoURL: https://intel.github.io/helm-charts
      chart: intel-device-plugins-gpu
      targetRevision: 0.36.0
      helm:
        valueFiles:
          - $values/cluster/core/intel-gpu-plugin/values.yaml
    - repoURL: https://github.com/Arsenikki/kuberseni-gitops
      targetRevision: feat/talos
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
