---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: kuberseni
  sources:
    - repoURL: https://traefik.github.io/charts
      chart: traefik
      targetRevision: 40.2.0
      helm:
        valueFiles:
          - $values/cluster/core/traefik/values.yaml
    - repoURL: https://github.com/Arsenikki/kuberseni-gitops
      targetRevision: feat/talos
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
