---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-admin-creds
  namespace: cloudnative-pg
type: kubernetes.io/basic-auth
data:
  username: ${SECRET_USERNAME}
  password: ${SECRET_POSTGRES_ADMIN_PASSWORD}
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-immich-creds
  namespace: cloudnative-pg
type: kubernetes.io/basic-auth
data:
  username: ${SECRET_POSTGRES_IMMICH_USERNAME}
  password: ${SECRET_POSTGRES_IMMICH_PASSWORD}
