---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: teleport-data
  namespace: teleport
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn-fast-replicated
