---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: teleport
  namespace: teleport
spec:
  chart:
    spec:
      chart: teleport-cluster
      version: 14.1.0
      sourceRef:
        kind: HelmRepository
        name: teleport-charts
        namespace: flux-system
  interval: 30m
  values:
    chartMode: standalone
    # Disable for now as the operator support is still lacking
    # See https://github.com/gravitational/teleport/issues/29480
    operator:
      enabled: false
    clusterName: teleport.${SECRET_DOMAIN}
    kubeClusterName: home-cluster
    proxyListenerMode: multiplex
    log:
      level: DEBUG
    auth_service:
      enabled: true
      type: github
    service:
      type: ClusterIP
    ingress:
      enabled: false
    highAvailability:
      certManager:
        enabled: true
        issuerKind: ClusterIssuer
        issuerName: letsencrypt-prod
    persistence:
      enabled: true
      existingClaimName: teleport-data
