---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: teleport
  namespace: teleport
spec:
  chart:
    spec:
      chart: teleport-cluster
      version: 14.1.0
      sourceRef:
        kind: HelmRepository
        name: teleport-charts
        namespace: flux-system
  interval: 30m
  values:
    clusterName: "teleport.arsenikki.xyz"
    kubeClusterName: "home-cluster"
    auth_service:
      enabled: true
      type: github
    persistence:
      enabled: true
      existingClaimName: "teleport-data"
