---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: teleport
  namespace: teleport
spec:
  chart:
    spec:
      chart: teleport-cluster
      version: 14.3.3
      sourceRef:
        kind: HelmRepository
        name: teleport-charts
        namespace: flux-system
  interval: 30m
  values:
    chartMode: standalone
    log:
      level: DEBUG
    # Disable Kubernetes operator mode for now as the feature is still limited.
    # See https://github.com/gravitational/teleport/issues/29480 for details.
    operator:
      enabled: false
    clusterName: teleport.arsenikki.xyz
    kubeClusterName: home-cluster
    authentication:
      type: local
    proxyListenerMode: multiplex
    service:
      type: ClusterIP
    podSecurityPolicy:
      enabled: false
    persistence:
      enabled: true
      existingClaimName: teleport-data
