---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: teleport
  namespace: teleport
spec:
  chart:
    spec:
      chart: teleport-cluster
      version: 14.3.3
      sourceRef:
        kind: HelmRepository
        name: teleport-charts
        namespace: flux-system
  interval: 30m
  values:
    chartMode: standalone
    # Disable for now as the operator support is still lacking
    # See https://github.com/gravitational/teleport/issues/29480
    operator:
      enabled: false
    log:
      level: INFO
    clusterName: teleport.arsenikki.xyz
    kubeClusterName: home-cluster
    authentication:
      type: github
    proxyListenerMode: multiplex
    service:
      type: ClusterIP
    ingress:
      enabled: true
      # Setting suppressAutomaticWildcards to true will not automatically add *.<clusterName> as a hostname served
      # by the Ingress. This may be desirable if you don't use Teleport Application Access.
      suppressAutomaticWildcards: false
    annotations:
      ingress:
        # Automatically generate TLS certificate
        kubernetes.io/tls-acme: "true"
    podSecurityPolicy:
      enabled: false
    persistence:
      enabled: true
      existingClaimName: teleport-data
