apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: teleport
  namespace: kube-system
  annotations:
    kubernetes.io/tls-acme: 'true'
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - teleport.arsenikki.xyz
      secretName: teleport-tls
  rules:
    - host: teleport.arsenikki.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: teleport
                port:
                  number: 3080
