---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: adguard-home
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: adguard-home
      version: 5.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: adguard/adguardhome
      tag: v0.107.5
    env:
      TZ: "Europe/Helsinki"
    service:
      dns-tcp:
        type: LoadBalancer
        annotations:
          metallb.universe.tf/allow-shared-ip: adguard-home
        externalIPs:
          - "${ADGUARD_HOME_LB}"
        externalTrafficPolicy: Local
      dns-udp:
        type: LoadBalancer
        annotations:
          metallb.universe.tf/allow-shared-ip: adguard-home
        externalIPs:
          - "${ADGUARD_HOME_LB}"
        externalTrafficPolicy: Local
    ingress:
      main:
        enabled: true
        annotations:
          # Use Traefik for ingress
          kubernetes.io/ingress.class: "traefik"
          # Use authelia-forward-auth middleware for authentication
          traefik.ingress.kubernetes.io/router.middlewares: "security-forwardauth-authelia@kubernetescrd"
          # Use default cluster-issuer
          kubernetes.io/tls-acme: "true"
          # Only allow websecure endpoint
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          # Set to passthrough TLS to backend service
          traefik.ingress.kubernetes.io/router.tls: "true"
        hosts:
          - host: "adguard-home.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "adguard-home.${SECRET_DOMAIN}"
    persistence:
      config:
        enabled: true
        existingClaim: adguard-home-config
        mountPath: /opt/adguardhome/conf
      data:
        enabled: true
        existingClaim: adguard-home-data
        mountPath: /opt/adguardhome/work
    resources:
      requests:
        memory: 300Mi
        cpu: 200m
      limits:
        memory: 1000Mi
