---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - grafana/ks.yaml
  - kube-prometheus-stack/ks.yaml
  - loki/ks.yaml
  # - prometheus/ks.yaml
  # - promtail/ks.yaml
  - pve-exporter/ks.yaml
  - namespace.yaml
