---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: default
  labels:
    app.kubernetes.io/name: homepage
data:
  bookmarks.yaml: |
    - Communication:
      - Discord:
        - icon: discord.png
          href: https://discord.com/app
    - Media:
      - YouTube:
        - icon: youtube.png
          href: https://youtube.com/feed/subscriptions
    - Reading:
      - Reddit:
        - icon: reddit.png
          href: https://reddit.com
    - Git:
      - kubesearch:
        - icon: kubernetes-dashboard.png
          href: https://kubesearch.dev
      - flux-cluster-template:
        - icon: github.png
          href: https://github.com/onedr0p/flux-cluster-template
  docker.yaml: ""
  kubernetes.yaml: |
    mode: cluster
  services.yaml: |
    - Media:
      - Plex:
          icon: plex.png
          href: https://plex.${SECRET_DOMAIN}
          siteMonitor: http://plex.media.svc.cluster.local:32400
          widget:
            type: plex
            url: http://plex.media.svc.cluster.local:32400
            key: ${SECRET_PLEX_TOKEN}
      - Sonarr:
          icon: sonarr.png
          href: https://sonarr.${SECRET_DOMAIN}
          siteMonitor: http://sonarr.media.svc.cluster.local:8989
          widget:
            type: sonarr
            url: http://sonarr.media.svc.cluster.local:8989
            key: ${SECRET_SONARR_API_KEY}
      - Radarr:
          icon: radarr.png
          href: https://radarr.${SECRET_DOMAIN}
          siteMonitor: http://radarr.media.svc.cluster.local:7878
          widget:
            type: radarr
            url: http://radarr.media.svc.cluster.local:7878
            key: ${SECRET_RADARR_API_KEY}
      - qBittorrent:
          icon: qbittorrent.png
          href: https://qbittorrent.${SECRET_DOMAIN}
          siteMonitor: http://qbittorrent.media.svc.cluster.local:8080
          widget:
            type: qbittorrent
            url: http://qbittorrent.media.svc.cluster.local:8080
  settings.yaml: |
    title: Dashboard
    theme: dark
    color: slate
    headerStyle: clean
    layout:
      Home:
        style: column
        icon: mdi-home-analytics
      Media:
        style: row
        columns: 4
  widgets.yaml: |
    - kubernetes:
        cluster:
          # Shows cluster-wide statistics
          show: true
          # Shows the aggregate CPU stats
          cpu: true
          # Shows the aggregate memory stats
          memory: true
          # Shows a custom label
          showLabel: true
          label: "cluster"
        nodes:
          # Shows node-specific statistics
          show: true
          # Shows the CPU for each node
          cpu: true
          # Shows the memory for each node
          memory: true
          # Shows the label, which is always the node name
          showLabel: true
    - search:
        provider: google
        focus: false
        target: _blank
    - greeting:
        text_size: xl
        text: "Welcome!"
    - datetime:
        text_size: l
        format:
          dateStyle: long
          timeStyle: short
          hourCycle: h23
