---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: default
  labels:
    app.kubernetes.io/name: homepage
data:
  bookmarks.yaml: |
    - Communication:
      - Discord:
        - icon: discord.png
          href: https://discord.com/app
    - Media:
      - YouTube:
        - icon: youtube.png
          href: https://youtube.com/feed/subscriptions
    - Reading:
      - Reddit:
        - icon: reddit.png
          href: https://reddit.com
    - Git:
      - kubesearch:
        - icon: kubernetes-dashboard.png
          href: https://kubesearch.dev
      - flux-cluster-template:
        - icon: github.png
          href: https://github.com/onedr0p/flux-cluster-template
  docker.yaml: ""
  kubernetes.yaml: |
    mode: cluster
  services.yaml: |
    - Media:
      - Plex:
          icon: plex.png
          href: https://plex.${SECRET_DOMAIN}
          widget:
            type: plex
            url: https://plex.media.svc.cluster.local
            token: ${SECRET_PLEX_TOKEN}
      - Sonarr:
          icon: sonarr.png
          href: https://sonarr.${SECRET_DOMAIN}
          widget:
            type: sonarr
            url: https://sonarr.media.svc.cluster.local
            key: ${SECRET_SONARR_API_KEY}
      - Radarr:
          icon: radarr.png
          href: https://radarr.${SECRET_DOMAIN}
          widget:
            type: radarr
            url: https://radarr.media.svc.cluster.local
            key: ${SECRET_RADARR_API_KEY}
      - qBittorrent:
          icon: qbittorrent.png
          href: https://qbittorrent.${SECRET_DOMAIN}
          widget:
            type: qbittorrent
            url: https://qbittorrent.media.svc.cluster.local
  settings.yaml: |
    title: Dashboard
    theme: dark
    color: slate
    headerStyle: clean
    layout:
      Home:
        style: column
        icon: mdi-home-analytics
      Network:
        style: row
        columns: 3
        icon: mdi-server
      Observability:
        style: column
        icon: mdi-chart-line
  widgets.yaml: |
    - resources:
        backend: kubernetes
        cpu: true
        expanded: true
        memory: true
    - search:
        provider: google
        focus: false
        target: _blank
    - greeting:
        text_size: xl
        text: "Welcome!"
    - datetime:
        text_size: l
        format:
          dateStyle: long
          timeStyle: short
          hourCycle: h23
