---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: default
  labels:
    app.kubernetes.io/name: homepage
data:
  bookmarks.yaml: |
    - Communitcate:
        - Discord:
            - icon: discord.png
              href: https://discord.com/app
    - Media:
        - YouTube:
            - icon: youtube.png
              href: https://youtube.com/feed/subscriptions
    - Reading:
        - Reddit:
            - icon: reddit.png
              href: https://reddit.com
    - Git:
        - kubesearch:
            - icon: kubernetes-dashboard.png
              href: https://kubesearch.dev
        - flux-cluster-template:
            - icon: github.png
              href: https://github.com/onedr0p/flux-cluster-template
  docker.yaml: ""
  kubernetes.yaml: |
    mode: cluster
  services.yaml: ""
  settings.yaml: |
    title: Dashboard
    theme: dark
    color: slate
    headerStyle: clean
    layout:
      Home:
        style: column
        icon: mdi-home-analytics
      Network:
        style: row
        columns: 3
        icon: mdi-server
      Observability:
        style: column
        icon: mdi-chart-line
  widgets.yaml: |
    - resources:
        backend: kubernetes
        cpu: true
        expanded: true
        memory: true
    - search:
        provider: ["duckduckgo"]
        focus: false
        target: _blank
    - greeting:
        text_size: xl
        text: "Welcome!"
    - datetime:
        text_size: l
        format:
          dateStyle: long
          timeStyle: short
          hourCycle: h23
