apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authelia
  namespace: security
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-charts
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    #initContainers:
    #  init-db:
    #    image: ghcr.io/onedr0p/postgres-initdb:14.6
    #    envFrom:
    #      - secretRef:
    #          name: authelia-secret
    controller:
      replicas: 3
      strategy: RollingUpdate
      annotations:
        reloader.stakater.com/auto: "true"
    image:
      repository: ghcr.io/authelia/authelia
      # TODO Switch to Authelia release tag on next release
      tag: master@sha256:1b096d11483b92a098c31eef5f779af583520c749428358de3e19567ebbe679d
    # envFrom:
    #   - secretRef:
    #       name: authelia-secret
    enableServiceLinks: false
    service:
      main:
        ports:
          http:
            port: 80
    ingress:
      main: 
        enabled: true
        annotations:
          # Use Traefik for ingress
          kubernetes.io/ingress.class: "traefik"
          # Use default cluster-issuer
          kubernetes.io/tls-acme: "true"
          # Only allow websecure endpoint
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          # Set to passthrough TLS to backend service
          traefik.ingress.kubernetes.io/router.tls: "true"
        hosts:
        - host: auth.${SECRET_DOMAIN}
          paths:
          - path: /
            pathType: Prefix
        tls:
        - secretName: authelia-tls
          hosts:
          - auth.${SECRET_DOMAIN}
    podSecurityContext:
      container:
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: "OnRootMismatch"
    persistence:
      config:
        enabled: true
        type: configMap
        name: authelia-configmap
        subPath: configuration.yml
        mountPath: /config/configuration.yml
        readOnly: false