apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: security
resources:
  - persistence
  - helm-release.yaml
patchesStrategicMerge:
  - ./patches/env.yaml
configMapGenerator:
  - name: authelia-config
    files:
      - ./config/configuration.yaml
  - name: authelia-users
    files:
      - ./config/users.yaml
generatorOptions:
  disableNameSuffixHash: true