---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vpn-gateway
  namespace: vpn
spec:
  interval: 15m
  chart:
    spec:
      chart: pod-gateway
      version: 6.0.0
      sourceRef:
        kind: HelmRepository
        name: angelnu-charts
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: ghcr.io/angelnu/pod-gateway
      tag: v1.8.1
    webhook:
      gatewayAnnotation: useVpnGateway
      gatewayDefault: false
      gatewayLabel: useVpnGateway
      image:
        repository: ghcr.io/angelnu/gateway-admision-controller
        tag: v3.7.0@sha256:985eb60fd0017f657d5e66707f7e9b3f764f3337a87a379d26cd15e950bd79ad
    DNS: 172.16.1.1
    addons:
      netshoot:
        enabled: true
      vpn:
        enabled: true
        type: gluetun
        image:
          # TODO: Replace with ghcr.io/qdm12/gluetun when a versioned tag is available
          repository: docker.io/qmcgaw/gluetun
          tag: v3.32.0
        env:
          - name: VPN_SERVICE_PROVIDER
            value: private internet access
          - name: VPN_TYPE
            value: wireguard
          - name: VPN_INTERFACE
            value: wg0
          - name: FIREWALL
            value: "off"
          - name: DOT
            value: "off"
          - name: LOG_LEVEL
            value: debug
        vpnConfig: |-
          [Interface]
          Address = 10.22.231.141
          PrivateKey = ${PIA_PRIVATE_KEY}
          DNS = 10.0.0.243,10.0.0.242

          [Peer]
          PublicKey = fUBH4Y4Xz7SnPTDHna4W84NWAxKcq/dhOccNA82/DHM=
          Endpoint = 188.126.89.152:1337
          AllowedIPs = 0.0.0.0/0
          PersistentKeepalive = 25
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
        networkPolicy:
          enabled: true
          egress:
            - to:
                - ipBlock:
                    cidr: 0.0.0.0/0
              ports:
                - port: 51820
                  protocol: UDP
            - to:
                - namespaceSelector: {}
    publicPorts:
      - IP: 10
        hostname: qbittorrent
        ports:
          - port: 56202
            type: udp
          - port: 56202
            type: tcp
    routed_namespaces: ["media"]
    settings:
      VPN_INTERFACE: "wg0"
      VPN_BLOCK_OTHER_TRAFFIC: "true"
      VPN_TRAFFIC_PORT: "51820"
      DNS_LOCAL_CIDRS: "local"
      NOT_ROUTED_TO_GATEWAY_CIDRS: 10.0.0.0/8 192.168.0.0/16
      VPN_LOCAL_CIDRS: 10.0.0.0/8 192.168.0.0/16
      VXLAN_ID: "43"
      VXLAN_IP_NETWORK: "172.16.1"