---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vpn-gateway
  namespace: vpn
spec:
  interval: 15m
  chart:
    spec:
      chart: pod-gateway
      version: 6.5.0
      sourceRef:
        kind: HelmRepository
        name: angelnu-charts
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    image:
      repository: ghcr.io/angelnu/pod-gateway
      tag: v1.8.1
    routed_namespaces: ["media"]
    settings:
      VPN_INTERFACE: tun0
    # VPN_BLOCK_OTHER_TRAFFIC: true
      NOT_ROUTED_TO_GATEWAY_CIDRS: "10.42.0.0/16 10.43.0.0/16"
      VPN_LOCAL_CIDRS: "10.0.0.0/8 192.168.0.0/16"
      VPN_TRAFFIC_PORT: "51820"
    # publicPorts:
    # - IP: 10
    #   hostname: qbittorrent-0
    #   ports:
    #   - port: 51820
    #     type: udp
    #   - port: 51820
    #     type: tcp
    additionalContainers:
      gluetun:
        image: qmcgaw/gluetun:v3.32
        env:
        - name: VPN_SERVICE_PROVIDER
          value: private internet access
        - name: SERVER_REGIONS
          value: Netherlands
        - name: OPENVPN_USER
          value: ${PIA_USERNAME}
        - name: OPENVPN_PASSWORD
          value: ${PIA_PASSWORD}
        - name: DOT
          value: "off"
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
    webhook:
      gatewayAnnotation: setGateway
      gatewayDefault: false
      gatewayLabel: setGateway
      image:
        repository: ghcr.io/angelnu/gateway-admision-controller
        tag: v3.7.0@sha256:985eb60fd0017f657d5e66707f7e9b3f764f3337a87a379d26cd15e950bd79ad