apiVersion: v1
kind: Secret
metadata:
    name: pia-wireguard-config
    namespace: vpn
type: Opaque
stringData:
    vpnConfigfile: ENC[AES256_GCM,data:3cC6L6YNUK2Hu+FiGB2yMY1oDyoLDv6kgpaebrQjD+LaguhXTAQywSl0lCX1/MGlCxuxTO7mLK0ET+VVdEzF8hK+VPoSkOarhX33554dajLAVh4s7GXcEO+OqgHHPtWOKsTUIoKgdUj1rYWmMAa7uD+YVcIfpCx6XHPGQNPec/IKr+lYk3REn6WI0Yrpeuw5zQb1GV4tLe9esLUq4s6TudR/ut6yZbdC+Tt9KhltgHaVbF+aVOhnicGw9bfixkBdgHlTvwmoh8hdkJQjo9dj+7Lvf+hvPBAZYq8l9TCfLJsOLtL9qa9ptafM9wTp1jvvK+yK7DaEedJNw8d4eNLi4PQY7QzPZDZNrQ==,iv:QmeCxIgCrEUKgEJGHiMi6G0J4q8eX8mx4rIV2l8seMQ=,tag:il+SFuv5Parfah41rPyxhw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17ax8w6axmjplnnf38t8qlqtz2uj2k685fwnl6uy6u8q2rwsjmd6qa6ddv9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0RDBxNFJaTXExMTdtR2Nm
            NXkvTjZIdjNRVEQ0SzNVdEpQOFN5V0FqVFJRClNmc1QxNE1kRkg0M0l2TnV5elhI
            dzc0SFNTSFBnZFRkN3Vaemw1ZVRHbXcKLS0tIE5qL2VKWjFYQzBqQjBZR0pRYW1k
            UmNDZUhpTXZVd3ZzNnd1OG5vVXl6cm8KsZ50HC90SN7VrIllG8KSPiRjAMYrVvVM
            KuxMUjzGPIdVZ8A3vMdhUzYmrpo6eAIgWY0UJhARd7HjA+Cr/BrgMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-19T09:44:56Z"
    mac: ENC[AES256_GCM,data:9Vx4FlYwWlz2nG+KeU7TY2C1Ztw8fnMpWs96qEj27rabVm6F+b220aToNF9U+qtqtpd09Yn7XzlF+l2YvvdfUamQcl5qQWe2iyj75GRbmFEo5GZTow0rM3SJK3nbVBnYEkF8bvslbeECkiAAwVP+QyrqLIjuYBn+rYdPUcfSnnU=,iv:otdbwrSF3LUGFINZViWfrUJUExTmEYJgFHhDBRigRTs=,tag:sf7voQeRZZEYvaeYXOlKJA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
