---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: media
spec:
  chart:
    spec:
      chart: app-template
      version: 1.3.1
      sourceRef:
        kind: HelmRepository
        name: bjw-charts
        namespace: flux-system
  interval: 30m
  values:
    image:
      repository: ghcr.io/onedr0p/qbittorrent
      tag: 4.5.1
    env:
      TZ: "Europe/Helsinki"
      WAIT_FOR_VPN: "true"
      QBITTORRENT__PORT: 8080
    service:
      main:
        ports:
          http:
            port: 8080
    ingress:
      main: 
        enabled: true
        annotations:
          # Use forward-auth middleware for authentication
          traefik.ingress.kubernetes.io/router.middlewares: "traefik-forward-auth@kubernetescrd"
          # Let external-dns manage cloudflare DNS records
          external-dns/is-public: "true"
        hosts:
        - host: qbittorrent.${SECRET_DOMAIN}
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - qbittorrent.${SECRET_DOMAIN}
    persistence:
      config:
        enabled: true
        existingClaim: qbittorrent-config
      media:
        enabled: true
        mountPath: /data
        existingClaim: media-pvc-01
      shared:
        enabled: true
        type: emptyDir
        mountPath: /shared
        medium: Memory
        sizeLimit: 10Mi
    addons:
      vpn:
        enabled: true
        type: gluetun
        gluetun:
          image:
            repository: docker.io/qmcgaw/gluetun
            tag: v3.32.0
        env: 
          VPN_SERVICE_PROVIDER: 'private internet access'
          OPENVPN_USER: '${OPENVPN_USERNAME}'
          OPENVPN_PASSWORD: '${OPENVPN_PASSWORD}'
          SERVER_REGIONS: Netherlands
        configFile: |-
          [Interface]
          PrivateKey = ${PIA_PRIVATE_KEY}
          Address = 10.13.225.89
          DNS = 10.0.0.243,10.0.0.242
          PostUp = /gluetun/scripts/up.sh %i
          PreDown = /gluetun/scripts/down.sh %i
          [Peer]
          PublicKey = ${PIA_PUBLIC_KEY}
          Endpoint = 188.126.89.79:1337
          AllowedIPs = 0.0.0.0/0
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
              - SYS_MODULE
        scripts:
          up: |-
            #!/bin/bash
            echo "connected" > /shared/vpnstatus
          down: |-
            #!/bin/bash
            echo "disconnected" > /shared/vpnstatus
    securityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 65539
    resources:
      requests:
        cpu: 100m
        memory: 128M
      limits:
        memory: 1024M