---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: media
spec:
  chart:
    spec:
      chart: app-template
      version: 1.3.1
      sourceRef:
        kind: HelmRepository
        name: bjw-charts
        namespace: flux-system
  interval: 30m
  values:
    controller:
      type: deployment
    image:
      repository: ghcr.io/onedr0p/qbittorrent
      tag: 4.5.2
    env:
      UMASK: "022"
      QBITTORRENT__PORT: 8080
      QBITTORRENT__USE_PROFILE: "true"
      PUID: 0
      PGID: 0
    sidecars:
      gluetun:
        image: qmcgaw/gluetun:v3.32
        env:
        - name: VPN_SERVICE_PROVIDER
          value: private internet access
        - name: SERVER_REGIONS
          value: Netherlands
        - name: OPENVPN_USER
          value: ${PIA_USERNAME}
        - name: OPENVPN_PASSWORD
          value: ${PIA_PASSWORD}
        - name: DOT
          value: "off"
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
    hostname: qbittorrent
    service:
      main:
        ports:
          http:
            port: 8080
    ingress:
      main: 
        enabled: true
        annotations:
          # Use forward-auth middleware for authentication
          traefik.ingress.kubernetes.io/router.middlewares: "traefik-forward-auth@kubernetescrd"
          # Let external-dns manage cloudflare DNS records
          external-dns/is-public: "true"
        hosts:
        - host: qbittorrent.${SECRET_DOMAIN}
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - qbittorrent.${SECRET_DOMAIN}
    persistence:
      config:
        enabled: true
        existingClaim: qbittorrent-config
      media:
        enabled: true
        mountPath: /data
        existingClaim: media-pvc-01
    securityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups: [10000]
    resources:
      requests:
        cpu: 100m
        memory: 128M
      limits:
        memory: 1500M