---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: security
spec:
  interval: 5m
  chart:
    spec:
      chart: vaultwarden
      version: 2.3.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: vaultwarden/server
      tag: 1.21.0
    env:
      DATA_FOLDER: "config"
      SIGNUPS_ALLOWED: false
      WEBSOCKET_ENABLED: true
      WEBSOCKET_ADDRESS: 0.0.0.0
      WEBSOCKET_PORT: 3012
      DOMAIN: https://vault.${SECRET_DOMAIN}
      ADMIN_TOKEN: ${SECRET_VAULTWARDEN_ADMIN_TOKEN}
      DATABASE_URL: postgresql://${SECRET_VAULTWARDEN_DB_USERNAME}:${SECRET_VAULTWARDEN_DB_PASSWORD}@vaultwarden-postgresql:5432/vaultwarden
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "traefik"
        hosts:
          - host: "vault.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  port: 80
              - path: /notifications/hub/negotiate
                pathType: Prefix
                service:
                  port: 80
              - path: /notifications/hub
                pathType: Prefix
                service:
                  port: 3012
        tls:
          - hosts:
              - "vault.${SECRET_DOMAIN}"
    persistence:
      config:
        enabled: true
        existingClaim: vaultwarden-config
    postgresql:
      enabled: true
      postgresqlUsername: "${SECRET_VAULTWARDEN_DB_USERNAME}"
      postgresqlPassword: "${SECRET_VAULTWARDEN_DB_PASSWORD}"
      postgresqlDatabase: "vaultwarden"
      persistence:
        enabled: true
        existingClaim: vaultwarden-psql-config
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 1000Mi
