---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home-automation
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: home-assistant
      version: 13.0.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/home-assistant/home-assistant
      tag: 2022.4.1
    env:
      TZ: "Europe/Helsinki"
    envFrom:
      - secretRef:
          name: home-assistant
    hostNetwork: true
    dnsPolicy: ClusterFirstWithHostNet
    service:
      main:
        enabled: true
        type: ClusterIP
        ports:
          http:
            enabled: true
            port: 8123
      udp:
        enabled: true
        type: ClusterIP
        ports:
          webrtc:
            enabled: true
            port: 54321
            protocol: UDP
    ingress:
      main:
        enabled: true
        annotations:
          # Use Traefik for ingress
          kubernetes.io/ingress.class: "traefik"
          # Use default cluster-issuer
          kubernetes.io/tls-acme: "true"
          # Only allow websecure endpoint
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          # Set to passthrough TLS to backend service
          traefik.ingress.kubernetes.io/router.tls: "true"
        hosts:
          - host: "homeassistant.${SECRET_DOMAIN}"
            paths:
              - path: /
        tls:
          - secretName: homeassistant-tls
            hosts:
              - "homeassistant.${SECRET_DOMAIN}"
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false
    persistence:
      config:
        enabled: true
        existingClaim: home-assistant-config
    addons:
      codeserver:
        enabled: false
        image:
          repository: docker.io/codercom/code-server
          tag: 4.3.0
        git:
          deployKeySecret: code-server
        env:
          TZ: "Europe/Helsinki"
        workingDir: "/config"
        args:
          - --auth
          - "none"
          - --user-data-dir
          - "/config/.vscode"
          - --extensions-dir
          - "/config/.vscode"
        ingress:
          enabled: true
          annotations:
            # Use Traefik for ingress
            kubernetes.io/ingress.class: "traefik"
            # Use authelia-forward-auth middleware for authentication
            traefik.ingress.kubernetes.io/router.middlewares: "security-forwardauth-authelia@kubernetescrd"
            # Use default cluster-issuer
            kubernetes.io/tls-acme: "true"
            # Only allow websecure endpoint
            traefik.ingress.kubernetes.io/router.entrypoints: websecure
            # Set to passthrough TLS to backend service
            traefik.ingress.kubernetes.io/router.tls: "true"
          hosts:
            - host: "codeserver.${SECRET_DOMAIN}"
              paths:
                - path: /
          tls:
            - secretName: ha-vscode-tls
              hosts:
                - "codeserver.${SECRET_DOMAIN}"
        volumeMounts:
          - name: config
            mountPath: /config
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        memory: 2000Mi
