apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home-automation
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.3.0
      sourceRef:
        kind: HelmRepository
        name: bjw-charts
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      type: statefulset
    image:
      repository: ghcr.io/home-assistant/home-assistant
      tag: 2022.4.1
    env:
      TZ: "Europe/Helsinki"
    service:
      main:
        ports:
          http:
            port: 8123
    ingress:
      main: 
        enabled: true
        annotations:
          # Let external-dns manage cloudflare DNS records
          external-dns/is-public: "true"
        hosts:
        - host: homeassistant.${SECRET_DOMAIN}
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - homeassistant.${SECRET_DOMAIN}
    ### Run as root for now
    # podSecurityContext:
    #   runAsUser: 568
    #   runAsGroup: 568
    #   fsGroup: 568
    #   fsGroupChangePolicy: "OnRootMismatch"
    persistence:
      config:
        enabled: true
        type: pvc
        existingClaim: home-assistant-config
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 2000Mi
    addons:
      codeserver:
        enabled: true
        image:
          repository: ghcr.io/coder/code-server
          tag: 4.9.1
          pullPolicy: IfNotPresent
        env:
          TZ: "Europe/Helsinki"
        args:
          - --auth
          - "none"
          - --user-data-dir
          - "/config/.vscode"
          - --extensions-dir
          - "/config/.vscode"
        volumeMounts:
        - name: config
          mountPath: /config
        ingress:
          enabled: true
          annotations:
            # Use forward-auth middleware for authentication
            traefik.ingress.kubernetes.io/router.middlewares: "traefik-forward-auth@kubernetescrd"
            # Let external-dns manage cloudflare DNS records
            external-dns/is-public: "true"
          hosts:
          - host: "codeserver.${SECRET_DOMAIN}"
            paths:
            - path: /
              pathType: Prefix
          tls:
          - hosts:
            - "codeserver.${SECRET_DOMAIN}"