apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: democratic-csi
  namespace: democratic-csi
spec:
  interval: 15m
  chart:
    spec:
      chart: democratic-csi
      version: 0.14.1
      sourceRef:
        kind: HelmRepository
        name: democratic-csi-charts
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    csiDriver:
      name: org.democratic-csi.nfs
    storageClasses:
      - name: truenas-nfs-csi
        defaultClass: true
        reclaimPolicy: Delete
        volumeBindingMode: Immediate
        allowVolumeExpansion: true
        parameters:
          fsType: nfs
        mountOptions:
          - noatime
          - nfsvers=4
    driver:
      config:
        driver: freenas-nfs
        instance_id:
        httpConnection:
          protocol: http
          host: ${TRUENAS_IP_ADDRESS}
          port: 80
          username: ${SECRET_TRUENAS_USER}
          password: ${SECRET_TRUENAS_PASSWORD}
          allowInsecure: true
        sshConnection:
          host: ${TRUENAS_IP_ADDRESS}
          port: 22
          username: ${SECRET_TRUENAS_USER}
          password: ${SECRET_TRUENAS_PASSWORD}
        zfs:
          datasetParentName: main/nfs/vols
          detachedSnapshotsDatasetParentName: main/nfs/snaps
          datasetEnableQuotas: true
          datasetEnableReservation: false
          datasetPermissionsMode: "0777"
          datasetPermissionsUser: 0
          datasetPermissionsGroup: 0
        nfs:
          shareHost: ${TRUENAS_IP_ADDRESS}
          shareAlldirs: false
          shareAllowedHosts: []
          shareAllowedNetworks: []
          shareMaprootUser: root
          shareMaprootGroup: wheel
          shareMapallUser: ""
          shareMapallGroup: ""