apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: democratic-csi
  namespace: democratic-csi
spec:
  interval: 15m
  chart:
    spec:
      chart: democratic-csi
      version: 0.14.1
      sourceRef:
        kind: HelmRepository
        name: democratic-csi-charts
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    driver:
      config:
        driver: freenas-nfs
        instance_id:
        httpConnection:
          protocol: http
          host: 192.168.1.2
          port: 80
          username: ${SECRET_TRUENAS_USER}
          password: ${SECRET_TRUENAS_PASSWORD}
          allowInsecure: true
        sshConnection:
          host: 192.168.1.2
          port: 22
          username: ${SECRET_TRUENAS_USER}
          password: ${SECRET_TRUENAS_PASSWORD}
        zfs:
          datasetParentName: main/nfs/vols
          detachedSnapshotsDatasetParentName: main/nfs/snaps
          datasetEnableQuotas: true
          datasetEnableReservation: false
          datasetPermissionsMode: "0777"
          datasetPermissionsUser: root
          datasetPermissionsGroup: wheel
        nfs:
          shareHost: 192.168.1.2
          shareAlldirs: false
          shareAllowedHosts: []
          shareAllowedNetworks: []
          shareMaprootUser: root
          shareMaprootGroup: wheel
          shareMapallUser: ""
          shareMapallGroup: ""