---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-pvc-01
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 14400Gi
  storageClassName: longhorn-slow
