---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-fast
provisioner: driver.longhorn.io
reclaimPolicy: Delete
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "480"
  diskSelector: "fast"
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-fast-replicated
provisioner: driver.longhorn.io
reclaimPolicy: Delete
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "480"
  diskSelector: "fast"
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-slow
provisioner: driver.longhorn.io
reclaimPolicy: Retain
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "480"
  diskSelector: "slow"
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-slow-replicated
provisioner: driver.longhorn.io
reclaimPolicy: Retain
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "480"
  diskSelector: "slow"
