---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pod-gateway
  namespace: vpn
spec:
  interval: 30m
  chart:
    spec:
      chart: pod-gateway
      version: 6.5.1
      sourceRef:
        kind: HelmRepository
        name: angelnu-charts
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: ghcr.io/angelnu/pod-gateway
      tag: v1.8.1@sha256:690b6365728fe9012ad4cdfca38334992664596513dca187d1b93d2025205776
    webhook:
      gatewayAnnotation: setGateway
      gatewayDefault: false
      gatewayLabel: setGateway
      image:
        repository: ghcr.io/angelnu/gateway-admision-controller
        tag: v3.7.0@sha256:985eb60fd0017f657d5e66707f7e9b3f764f3337a87a379d26cd15e950bd79ad
    DNS: 172.16.1.1
    addons:
      netshoot:
        enabled: true
        resources:
          requests:
            cpu: 5m
            memory: 10M
          limits:
            memory: 10M
      vpn:
        enabled: true
        type: gluetun
        image:
          repository: ghcr.io/qdm12/gluetun
          tag: v3.35.0@sha256:a98d1ec99e09a1b806aff7f0c3d8a133a8ede7d3d7a250b62029a39a61f01525
        env:
          - name: VPN_SERVICE_PROVIDER
            value: mullvad
          - name: VPN_TYPE
            value: wireguard
          - name: VPN_INTERFACE
            value: wg0
          - name: FIREWALL
            value: "off"
          - name: DOT
            value: "off"
          - name: SERVER_CITIES
            value: Amsterdam
          - name: WIREGUARD_PRIVATE_KEY
            value: ${SECRET_WG_PRIVATE_KEY}
          - name: WIREGUARD_ADDRESSES
            value: ${SECRET_WG_ADDRESSES}
          - name: LOG_LEVEL
            value: debug
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
    routed_namespaces:
      - media
    settings:
      VPN_INTERFACE: "wg0"
      VXLAN_ID: "43"
      VXLAN_IP_NETWORK: "172.16.1"
      VPN_BLOCK_OTHER_TRAFFIC: "false"
      VPN_TRAFFIC_PORT: "51820"
      DNS_LOCAL_CIDRS: "local"
      NOT_ROUTED_TO_GATEWAY_CIDRS: "10.0.0.0/8 192.168.0.0/16"
      VPN_LOCAL_CIDRS: "10.0.0.0/8 192.168.0.0/16"
