---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pod-gateway
  namespace: vpn
spec:
  interval: 30m
  chart:
    spec:
      chart: pod-gateway
      version: 6.5.1
      sourceRef:
        kind: HelmRepository
        name: angelnu-charts
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: ghcr.io/angelnu/pod-gateway
      tag: v1.8.1@sha256:690b6365728fe9012ad4cdfca38334992664596513dca187d1b93d2025205776
    webhook:
      image:
        repository: ghcr.io/angelnu/gateway-admision-controller
        tag: v3.9.0@sha256:4e169da5af107a9c6c784d3e03c89da07fad45f18358ab5b7177662df12d955a
    addons:
      vpn:
        enabled: true
        type: gluetun
        gluetun:
          image:
            repository: docker.io/qmcgaw/gluetun
            tag: v3.34.3@sha256:55f6c5b9cd2646b7d3f95c48f2d35e9e01fefa5d927f8636392e104f6d86639b
        env:
          - name: VPN_SERVICE_PROVIDER
            value: private internet access
          - name: SERVER_REGIONS
            value: Netherlands
          - name: OPENVPN_USER
            value: ${PIA_USERNAME}
          - name: OPENVPN_PASSWORD
            value: ${PIA_PASSWORD}
          - name: VPN_TYPE
            value: openvpn
          - name: OPENVPN_PROTOCOL
            value: udp
          # Currently need this in K8s to hit Cluster DNS for lookup
          - name: FIREWALL
            value: "off"
          # Currently need this in K8s to hit Cluster DNS for lookup
          - name: DOT
            value: "off"
          - name: LOG_LEVEL
            value: debug
        securityContext:
          # Gluetun won't run on-top of Talos / Cilium w/o this atm
          privileged: true
      networkPolicy:
        # Using my own Cilium-based Network Policies
        enabled: false
    # clusterName: ${CLUSTER_DOMAIN}
    # Needed to get CoreDNS IP listed in /etc/resolv.conf for NAS DNS lookup when mounting SMB share
    DNSPolicy: ClusterFirst
    routed_namespaces:
      - media
    settings:
      # Don't forget to allow this on your firewall(s)!
      VPN_TRAFFIC_PORT: 51820
      VPN_LOCAL_CIDRS: 10.0.0.0/8 192.168.0.0/16
      NOT_ROUTED_TO_GATEWAY_CIDRS: 10.0.0.0/8 192.168.0.0/16