---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pod-gateway
  namespace: vpn
spec:
  interval: 30m
  chart:
    spec:
      chart: pod-gateway
      version: 6.5.1
      sourceRef:
        kind: HelmRepository
        name: angelnu-charts
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: ghcr.io/angelnu/pod-gateway
      tag: v1.8.1@sha256:690b6365728fe9012ad4cdfca38334992664596513dca187d1b93d2025205776
    webhook:
      image:
        repository: ghcr.io/angelnu/gateway-admision-controller
        tag: v3.9.0@sha256:4e169da5af107a9c6c784d3e03c89da07fad45f18358ab5b7177662df12d955a
    DNS: 172.16.1.1
    addons:
      vpn:
        enabled: true
        type: gluetun
        gluetun:
          image:
            repository: docker.io/qmcgaw/gluetun
            tag: v3.34.3@sha256:55f6c5b9cd2646b7d3f95c48f2d35e9e01fefa5d927f8636392e104f6d86639b
        env:
          - name: VPN_SERVICE_PROVIDER
            value: mullvad
          - name: VPN_TYPE
            value: wireguard
          - name: VPN_INTERFACE
            value: wg0
          - name: FIREWALL
            value: "off"
          - name: DOT
            value: "off"
          - name: SERVER_CITIES
            value: Amsterdam
          - name: WIREGUARD_PRIVATE_KEY
            value: ${SECRET_WG_PRIVATE_KEY}
          - name: WIREGUARD_ADDRESSES
            value: ${SECRET_WG_ADDRESSES}
          - name: LOG_LEVEL
            value: debug
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
    publicPorts:
      - IP: 10
        hostname: qbittorrent-0
        ports:
          - port: 56202
            type: udp
          - port: 56202
            type: tcp
    DNSPolicy: ClusterFirst
    routed_namespaces:
      - media
    settings:
      VPN_INTERFACE: "wg0"
      VXLAN_ID: "43"
      VXLAN_IP_NETWORK: "172.16.1"
      VPN_BLOCK_OTHER_TRAFFIC: "true"
      VPN_TRAFFIC_PORT: "51820"
      DNS_LOCAL_CIDRS: "local"
      NOT_ROUTED_TO_GATEWAY_CIDRS: "10.0.0.0/8 192.168.0.0/16"
      VPN_LOCAL_CIDRS: "10.0.0.0/8 192.168.0.0/16"
      IPTABLES_NFT: "yes"