apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: pve-exporter
  namespace: monitoring
spec:
  staticConfigs:
    - targets:
        - 192.168.1.10
        - 192.168.1.11
        - 192.168.1.12
  relabelings: # relabel_configs
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: 127.0.0.1:9221  # PVE exporter.
  metricsPath: /pve