apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pve-exporter
  namespace: monitoring
spec:
  endpoints:
  - interval: 10s
    params:
      target:
      - 192.168.1.10
    path: /pve
    port: http
    scheme: http
  - interval: 10s
    params:
      target:
      - 192.168.1.11
    path: /pve
    port: http
    scheme: http
  - interval: 10s
    params:
      target:
      - 192.168.1.12
    path: /pve
    port: http
    scheme: http
  jobLabel: k8s-app
  namespaceSelector:
    matchNames:
    - monitoring
  selector:
    matchLabels:
      app.kubernetes.io/name: pve-exporter