---
apiVersion: v1
kind: ConfigMap
metadata:
  name: authentik-blueprints
  namespace: authentik
data:
  app-bazarr.yaml: "---\nversion: 1\nmetadata:\n  name: &app bazarr\nentries:\n  -\
    \ id: provider\n    model: authentik_providers_proxy.proxyprovider\n    identifiers:\n\
    \      name: *app\n    attrs:\n      authorization_flow:\n        !Find [authentik_flows.flow,\
    \ [slug, \"default-provider-authorization-implicit-consent\"]]\n      signing_key:\n\
    \        !Find [authentik_crypto.certificatekeypair, [name, \"authentik Self-signed\
    \ Certificate\"]]\n      invalidation_flow:\n        !Find [authentik_flows.flow,\
    \ [slug, \"default-provider-invalidation-flow\"]]\n      mode: proxy\n      internal_host:\
    \ http://bazarr.media.svc.cluster.local:6767\n      external_host: https://bazarr.homelab.arsenikki.casa\n\
    \      access_token_validity: hours=1\n\n  - id: application\n    model: authentik_core.application\n\
    \    identifiers:\n      slug: *app\n    attrs:\n      name: *app\n      group:\
    \ Apps\n      icon: https://raw.githubusercontent.com/morpheus65535/bazarr/master/frontend/public/images/favicon.ico\n\
    \      provider: !KeyOf provider\n      policy_engine_mode: any\n"
  app-home-assistant.yaml: "---\nversion: 1\nmetadata:\n  name: &app home-assistant\n\
    entries:\n  - id: provider\n    model: authentik_providers_proxy.proxyprovider\n\
    \    identifiers:\n      name: *app\n    attrs:\n      authorization_flow:\n \
    \       !Find [authentik_flows.flow, [slug, \"default-provider-authorization-implicit-consent\"\
    ]]\n      signing_key:\n        !Find [authentik_crypto.certificatekeypair, [name,\
    \ \"authentik Self-signed Certificate\"]]\n      invalidation_flow:\n        !Find\
    \ [authentik_flows.flow, [slug, \"default-provider-invalidation-flow\"]]\n   \
    \   mode: proxy\n      internal_host: http://home-assistant.home-automation.svc.cluster.local:8123\n\
    \      external_host: https://homeassistant.homelab.arsenikki.casa\n      access_token_validity:\
    \ hours=1\n\n  - id: application\n    model: authentik_core.application\n    identifiers:\n\
    \      slug: *app\n    attrs:\n      name: *app\n      group: Apps\n      icon:\
    \ https://brands.home-assistant.io/_/homeassistant/icon.png\n      provider: !KeyOf\
    \ provider\n      policy_engine_mode: any\n"
  app-lidarr.yaml: "---\nversion: 1\nmetadata:\n  name: &app lidarr\nentries:\n  -\
    \ id: provider\n    model: authentik_providers_proxy.proxyprovider\n    identifiers:\n\
    \      name: *app\n    attrs:\n      authorization_flow:\n        !Find [authentik_flows.flow,\
    \ [slug, \"default-provider-authorization-implicit-consent\"]]\n      signing_key:\n\
    \        !Find [authentik_crypto.certificatekeypair, [name, \"authentik Self-signed\
    \ Certificate\"]]\n      invalidation_flow:\n        !Find [authentik_flows.flow,\
    \ [slug, \"default-provider-invalidation-flow\"]]\n      mode: proxy\n      internal_host:\
    \ http://lidarr.media.svc.cluster.local:8686\n      external_host: https://lidarr.homelab.arsenikki.casa\n\
    \      access_token_validity: hours=1\n\n  - id: application\n    model: authentik_core.application\n\
    \    identifiers:\n      slug: *app\n    attrs:\n      name: *app\n      group:\
    \ Apps\n      icon: https://avatars.githubusercontent.com/u/28475832?s=48&v=4\n\
    \      provider: !KeyOf provider\n      policy_engine_mode: any\n"
  app-n8n.yaml: "---\nversion: 1\nmetadata:\n  name: &app n8n\nentries:\n  - id: provider\n\
    \    model: authentik_providers_proxy.proxyprovider\n    identifiers:\n      name:\
    \ *app\n    attrs:\n      authorization_flow:\n        !Find [\n          authentik_flows.flow,\n\
    \          [slug, \"default-provider-authorization-implicit-consent\"],\n    \
    \    ]\n      signing_key:\n        !Find [\n          authentik_crypto.certificatekeypair,\n\
    \          [name, \"authentik Self-signed Certificate\"],\n        ]\n      invalidation_flow:\n\
    \        !Find [\n          authentik_flows.flow,\n          [slug, \"default-provider-invalidation-flow\"\
    ],\n        ]\n      mode: proxy\n      internal_host: http://n8n.n8n.svc.cluster.local:5678\n\
    \      external_host: https://n8n.homelab.arsenikki.casa\n      access_token_validity:\
    \ hours=1\n\n  - id: application\n    model: authentik_core.application\n    identifiers:\n\
    \      slug: *app\n    attrs:\n      name: *app\n      group: Apps\n      icon:\
    \ https://repository-images.githubusercontent.com/193215554/df34b36d-279c-496c-91c2-959dd9c9f13d\n\
    \      provider: !KeyOf provider\n      policy_engine_mode: any\n"
  app-nodered.yaml: "---\nversion: 1\nmetadata:\n  name: &app nodered\nentries:\n\
    \  - id: provider\n    model: authentik_providers_proxy.proxyprovider\n    identifiers:\n\
    \      name: *app\n    attrs:\n      authorization_flow:\n        !Find [\n  \
    \        authentik_flows.flow,\n          [slug, \"default-provider-authorization-implicit-consent\"\
    ],\n        ]\n      signing_key:\n        !Find [\n          authentik_crypto.certificatekeypair,\n\
    \          [name, \"authentik Self-signed Certificate\"],\n        ]\n      invalidation_flow:\n\
    \        !Find [\n          authentik_flows.flow,\n          [slug, \"default-provider-invalidation-flow\"\
    ],\n        ]\n      mode: proxy\n      internal_host: http://node-red.home-automation.svc.cluster.local:1880\n\
    \      external_host: https://nodered.homelab.arsenikki.casa\n      access_token_validity:\
    \ hours=1\n\n  - id: application\n    model: authentik_core.application\n    identifiers:\n\
    \      slug: *app\n    attrs:\n      name: *app\n      group: Apps\n      icon:\
    \ https://repository-images.githubusercontent.com/193215554/df34b36d-279c-496c-91c2-959dd9c9f13d\n\
    \      provider: !KeyOf provider\n      policy_engine_mode: any\n"
  app-overseerr.yaml: "---\nversion: 1\nmetadata:\n  name: &app overseerr\nentries:\n\
    \  - id: provider\n    model: authentik_providers_proxy.proxyprovider\n    identifiers:\n\
    \      name: *app\n    attrs:\n      authorization_flow:\n        !Find [authentik_flows.flow,\
    \ [slug, \"default-provider-authorization-implicit-consent\"]]\n      signing_key:\n\
    \        !Find [authentik_crypto.certificatekeypair, [name, \"authentik Self-signed\
    \ Certificate\"]]\n      invalidation_flow:\n        !Find [authentik_flows.flow,\
    \ [slug, \"default-provider-invalidation-flow\"]]\n      mode: proxy\n      internal_host:\
    \ http://overseerr.media.svc.cluster.local:5055\n      external_host: https://overseerr.homelab.arsenikki.casa\n\
    \      access_token_validity: hours=1\n\n  - id: application\n    model: authentik_core.application\n\
    \    identifiers:\n      slug: *app\n    attrs:\n      name: *app\n      group:\
    \ Apps\n      icon: https://raw.githubusercontent.com/sct/overseerr/develop/public/favicon.ico\n\
    \      provider: !KeyOf provider\n      policy_engine_mode: any\n"
  app-prowlarr.yaml: "---\nversion: 1\nmetadata:\n  name: &app prowlarr\nentries:\n\
    \  - id: provider\n    model: authentik_providers_proxy.proxyprovider\n    identifiers:\n\
    \      name: *app\n    attrs:\n      authorization_flow:\n        !Find [\n  \
    \        authentik_flows.flow,\n          [slug, \"default-provider-authorization-implicit-consent\"\
    ],\n        ]\n      signing_key:\n        !Find [\n          authentik_crypto.certificatekeypair,\n\
    \          [name, \"authentik Self-signed Certificate\"],\n        ]\n      invalidation_flow:\n\
    \        !Find [\n          authentik_flows.flow,\n          [slug, \"default-provider-invalidation-flow\"\
    ],\n        ]\n      mode: proxy\n      internal_host: http://prowlarr.media.svc.cluster.local:9696\n\
    \      external_host: https://prowlarr.homelab.arsenikki.casa\n      access_token_validity:\
    \ hours=1\n\n  - id: application\n    model: authentik_core.application\n    identifiers:\n\
    \      slug: *app\n    attrs:\n      name: *app\n      group: Apps\n      icon:\
    \ https://raw.githubusercontent.com/Prowlarr/Prowlarr/develop/Logo/128.png\n \
    \     provider: !KeyOf provider\n      policy_engine_mode: any\n"
  app-qbittorrent.yaml: "---\nversion: 1\nmetadata:\n  name: &app qbittorrent\nentries:\n\
    \  - id: provider\n    model: authentik_providers_proxy.proxyprovider\n    identifiers:\n\
    \      name: *app\n    attrs:\n      authorization_flow:\n        !Find [\n  \
    \        authentik_flows.flow,\n          [slug, \"default-provider-authorization-implicit-consent\"\
    ],\n        ]\n      signing_key:\n        !Find [\n          authentik_crypto.certificatekeypair,\n\
    \          [name, \"authentik Self-signed Certificate\"],\n        ]\n      invalidation_flow:\n\
    \        !Find [\n          authentik_flows.flow,\n          [slug, \"default-provider-invalidation-flow\"\
    ],\n        ]\n      mode: proxy\n      internal_host: http://qbittorrent.media.svc.cluster.local:8080\n\
    \      external_host: https://qbittorrent.homelab.arsenikki.casa\n      access_token_validity:\
    \ hours=1\n\n  - id: application\n    model: authentik_core.application\n    identifiers:\n\
    \      slug: *app\n    attrs:\n      name: *app\n      group: Apps\n      icon:\
    \ https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/New_qBittorrent_Logo.svg/2048px-New_qBittorrent_Logo.svg.png\n\
    \      provider: !KeyOf provider\n      policy_engine_mode: any\n"
  app-radarr.yaml: "---\nversion: 1\nmetadata:\n  name: &app radarr\nentries:\n  -\
    \ id: provider\n    model: authentik_providers_proxy.proxyprovider\n    identifiers:\n\
    \      name: *app\n    attrs:\n      basic_auth_enabled: true\n      basic_auth_user_attribute:\
    \ radarr_user\n      basic_auth_password_attribute: radarr_password\n      authorization_flow:\n\
    \        !Find [\n          authentik_flows.flow,\n          [slug, \"default-provider-authorization-implicit-consent\"\
    ],\n        ]\n      signing_key:\n        !Find [\n          authentik_crypto.certificatekeypair,\n\
    \          [name, \"authentik Self-signed Certificate\"],\n        ]\n      invalidation_flow:\n\
    \        !Find [\n          authentik_flows.flow,\n          [slug, \"default-provider-invalidation-flow\"\
    ],\n        ]\n      mode: proxy\n      internal_host: http://radarr.media.svc.cluster.local:7878\n\
    \      external_host: https://radarr.homelab.arsenikki.casa\n      access_token_validity:\
    \ hours=1\n\n  - id: application\n    model: authentik_core.application\n    identifiers:\n\
    \      slug: *app\n    attrs:\n      name: *app\n      group: Apps\n      icon:\
    \ https://avatars.githubusercontent.com/u/25025331?s=48&v=4\n      provider: !KeyOf\
    \ provider\n      policy_engine_mode: any\n"
  app-readarr.yaml: "---\nversion: 1\nmetadata:\n  name: &app readarr\nentries:\n\
    \  - id: provider\n    model: authentik_providers_proxy.proxyprovider\n    identifiers:\n\
    \      name: *app\n    attrs:\n      authorization_flow:\n        !Find [authentik_flows.flow,\
    \ [slug, \"default-provider-authorization-implicit-consent\"]]\n      signing_key:\n\
    \        !Find [authentik_crypto.certificatekeypair, [name, \"authentik Self-signed\
    \ Certificate\"]]\n      invalidation_flow:\n        !Find [authentik_flows.flow,\
    \ [slug, \"default-provider-invalidation-flow\"]]\n      mode: proxy\n      internal_host:\
    \ http://readarr.media.svc.cluster.local:8787\n      external_host: https://readarr.homelab.arsenikki.casa\n\
    \      access_token_validity: hours=1\n\n  - id: application\n    model: authentik_core.application\n\
    \    identifiers:\n      slug: *app\n    attrs:\n      name: *app\n      group:\
    \ Apps\n      icon: https://avatars.githubusercontent.com/u/57811956?s=48&v=4\n\
    \      provider: !KeyOf provider\n      policy_engine_mode: any\n"
  app-sonarr.yaml: "---\nversion: 1\nmetadata:\n  name: &app sonarr\nentries:\n  -\
    \ id: provider\n    model: authentik_providers_proxy.proxyprovider\n    identifiers:\n\
    \      name: *app\n    attrs:\n      basic_auth_enabled: true\n      basic_auth_user_attribute:\
    \ sonarr_user\n      basic_auth_password_attribute: sonarr_password\n      authorization_flow:\n\
    \        !Find [\n          authentik_flows.flow,\n          [slug, \"default-provider-authorization-implicit-consent\"\
    ],\n        ]\n      signing_key:\n        !Find [\n          authentik_crypto.certificatekeypair,\n\
    \          [name, \"authentik Self-signed Certificate\"],\n        ]\n      invalidation_flow:\n\
    \        !Find [\n          authentik_flows.flow,\n          [slug, \"default-provider-invalidation-flow\"\
    ],\n        ]\n      mode: proxy\n      internal_host: http://sonarr.media.svc.cluster.local:8989\n\
    \      external_host: https://sonarr.homelab.arsenikki.casa\n      access_token_validity:\
    \ hours=1\n\n  - id: application\n    model: authentik_core.application\n    identifiers:\n\
    \      slug: *app\n    attrs:\n      name: *app\n      group: Apps\n      icon:\
    \ https://avatars.githubusercontent.com/u/1082903?s=48&v=4\n      provider: !KeyOf\
    \ provider\n      policy_engine_mode: any\n"
  app-whoami.yaml: "---\nversion: 1\nmetadata:\n  name: &app whoami\nentries:\n  -\
    \ id: provider\n    model: authentik_providers_proxy.proxyprovider\n    identifiers:\n\
    \      name: *app\n    attrs:\n      authorization_flow:\n        !Find [\n  \
    \        authentik_flows.flow,\n          [slug, \"default-provider-authorization-implicit-consent\"\
    ],\n        ]\n      signing_key:\n        !Find [\n          authentik_crypto.certificatekeypair,\n\
    \          [name, \"authentik Self-signed Certificate\"],\n        ]\n      invalidation_flow:\n\
    \        !Find [\n          authentik_flows.flow,\n          [slug, \"default-provider-invalidation-flow\"\
    ],\n        ]\n      mode: proxy\n      internal_host: http://whoami.authentik.svc.cluster.local:80\n\
    \      external_host: https://whoami.homelab.arsenikki.casa\n      access_token_validity:\
    \ hours=1\n\n  - id: application\n    model: authentik_core.application\n    identifiers:\n\
    \      slug: *app\n    attrs:\n      name: *app\n      group: Apps\n      icon:\
    \ https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/whats-up-docker.png\n\
    \      provider: !KeyOf provider\n      policy_engine_mode: any\n"
  app-zigbee2mqtt.yaml: "---\nversion: 1\nmetadata:\n  name: &app zigbee2mqtt\nentries:\n\
    \  - id: provider\n    model: authentik_providers_proxy.proxyprovider\n    identifiers:\n\
    \      name: *app\n    attrs:\n      authorization_flow:\n        !Find [\n  \
    \        authentik_flows.flow,\n          [slug, \"default-provider-authorization-implicit-consent\"\
    ],\n        ]\n      signing_key:\n        !Find [\n          authentik_crypto.certificatekeypair,\n\
    \          [name, \"authentik Self-signed Certificate\"],\n        ]\n      invalidation_flow:\n\
    \        !Find [\n          authentik_flows.flow,\n          [slug, \"default-provider-invalidation-flow\"\
    ],\n        ]\n      mode: proxy\n      internal_host: http://zigbee2mqtt.home-automation.svc.cluster.local:8080\n\
    \      external_host: https://zigbee.homelab.arsenikki.casa\n      access_token_validity:\
    \ hours=1\n\n  - id: application\n    model: authentik_core.application\n    identifiers:\n\
    \      slug: *app\n    attrs:\n      name: *app\n      group: Apps\n      icon:\
    \ https://repository-images.githubusercontent.com/193215554/df34b36d-279c-496c-91c2-959dd9c9f13d\n\
    \      provider: !KeyOf provider\n      policy_engine_mode: any\n"
  embedded-outpost.yaml: "---\nversion: 1\nmetadata:\n  name: update-embedded-outpost\n\
    entries:\n  # Apply all app blueprints first\n  - model: authentik_blueprints.metaapplyblueprint\n\
    \    attrs:\n      identifiers:\n        name: bazarr\n      required: true\n\
    \  - model: authentik_blueprints.metaapplyblueprint\n    attrs:\n      identifiers:\n\
    \        name: home-assistant\n      required: true\n  - model: authentik_blueprints.metaapplyblueprint\n\
    \    attrs:\n      identifiers:\n        name: lidarr\n      required: true\n\
    \  - model: authentik_blueprints.metaapplyblueprint\n    attrs:\n      identifiers:\n\
    \        name: nodered\n      required: true\n  - model: authentik_blueprints.metaapplyblueprint\n\
    \    attrs:\n      identifiers:\n        name: overseerr\n      required: true\n\
    \  - model: authentik_blueprints.metaapplyblueprint\n    attrs:\n      identifiers:\n\
    \        name: prowlarr\n      required: true\n  - model: authentik_blueprints.metaapplyblueprint\n\
    \    attrs:\n      identifiers:\n        name: qbittorrent\n      required: true\n\
    \  - model: authentik_blueprints.metaapplyblueprint\n    attrs:\n      identifiers:\n\
    \        name: radarr\n      required: true\n  - model: authentik_blueprints.metaapplyblueprint\n\
    \    attrs:\n      identifiers:\n        name: readarr\n      required: true\n\
    \  - model: authentik_blueprints.metaapplyblueprint\n    attrs:\n      identifiers:\n\
    \        name: sonarr\n      required: true\n  - model: authentik_blueprints.metaapplyblueprint\n\
    \    attrs:\n      identifiers:\n        name: zigbee2mqtt\n      required: true\n\
    \n  # Configure the embedded outpost with all proxy providers\n  - model: authentik_outposts.outpost\n\
    \    state: present\n    identifiers:\n      name: \"authentik Embedded Outpost\"\
    \n    attrs:\n      providers:\n        - !Find [authentik_providers_proxy.proxyprovider,\
    \ [name, \"bazarr\"]]\n        - !Find [authentik_providers_proxy.proxyprovider,\
    \ [name, \"home-assistant\"]]\n        - !Find [authentik_providers_proxy.proxyprovider,\
    \ [name, \"lidarr\"]]\n        - !Find [authentik_providers_proxy.proxyprovider,\
    \ [name, \"nodered\"]]\n        - !Find [authentik_providers_proxy.proxyprovider,\
    \ [name, \"overseerr\"]]\n        - !Find [authentik_providers_proxy.proxyprovider,\
    \ [name, \"prowlarr\"]]\n        - !Find [authentik_providers_proxy.proxyprovider,\
    \ [name, \"qbittorrent\"]]\n        - !Find [authentik_providers_proxy.proxyprovider,\
    \ [name, \"radarr\"]]\n        - !Find [authentik_providers_proxy.proxyprovider,\
    \ [name, \"readarr\"]]\n        - !Find [authentik_providers_proxy.proxyprovider,\
    \ [name, \"sonarr\"]]\n        - !Find [authentik_providers_proxy.proxyprovider,\
    \ [name, \"zigbee2mqtt\"]]\n      config:\n        authentik_host: https://authentik.homelab.arsenikki.casa\n\
    \        kubernetes_ingress_annotations:\n          kubernetes.io/tls-acme: \"\
    true\"\n"
