---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homer-config
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-fast-replicated
  resources:
    requests:
      storage: 128Mi
