---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  chart:
    spec:
      chart: app-template
      version: 1.3.0
      sourceRef:
        kind: HelmRepository
        name: bjw-charts
        namespace: flux-system
  interval: 30m
  values:
    image:
      repository: ghcr.io/onedr0p/plex
      tag: 1.31.0.6654-02189b09f@sha256:e008f8822f31a5648ea5b28289ca82388e9111db4418a2662d7fb52ab9e61712
    service:
      main:
        type: LoadBalancer
        externalTrafficPolicy: Local
        loadBalancerIP: "${PLEX_LB}"
        ports:
          http:
            port: 32400
    ingress:
      main: 
        enabled: true
        annotations:
          # Let external-dns manage cloudflare DNS records
          external-dns/is-public: "true"
        hosts:
        - host: plex.${SECRET_DOMAIN}
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - plex.${SECRET_DOMAIN}
    persistence:
      config:
        enabled: true
        existingClaim: plex-config
      media:
        enabled: true
        mountPath: /data
        existingClaim: media-pvc-01
      transcode:
        enabled: true
        type: emptyDir
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: OnRootMismatch
      supplementalGroups: [44, 109, 10000]
    nodeSelector:
      kubernetes.io/hostname: magnus
    resources:
      requests:
        cpu: 1
        memory: 4000Mi
      limits:
        memory: 8000Mi
