---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-resources
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: kuberseni
  source:
    repoURL: https://github.com/Arsenikki/kuberseni-gitops
    targetRevision: feat/talos
    path: cluster/apps/traefik/resources
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
    directory:
      exclude: "argocd-app.yaml"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
