---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: arsenikki-casa
  namespace: traefik
spec:
  secretName: arsenikki-casa-tls
  privateKey:
    rotationPolicy: Always
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "arsenikki.casa"
  dnsNames:
    - "arsenikki.casa"
    - "*.arsenikki.casa"
