clusterName: kuberseni
# renovate: datasource=github-releases depName=siderolabs/talos
talosVersion: v1.12.6
# renovate: datasource=github-releases depName=siderolabs/kubernetes
kubernetesVersion: v1.35.2

# VIP shared across all control plane nodes
endpoint: https://192.168.1.40:6443

additionalApiServerCertSans:
  - 192.168.1.40

nodes:
  - hostname: control-plane-01
    ipAddress: 192.168.1.41
    installDisk: /dev/sda # verify with: talosctl get disks --insecure --nodes 192.168.1.41
    controlPlane: true
    networkInterfaces:
      - interface: eth0 # verify interface name in Talos maintenance mode
        dhcp: false
        addresses:
          - 192.168.1.41/24
        routes:
          - network: 0.0.0.0/0
            gateway: 192.168.1.1
        vip:
          ip: 192.168.1.40

  - hostname: control-plane-02
    ipAddress: 192.168.1.42
    installDisk: /dev/sda
    controlPlane: true
    networkInterfaces:
      - interface: eth0
        dhcp: false
        addresses:
          - 192.168.1.42/24
        routes:
          - network: 0.0.0.0/0
            gateway: 192.168.1.1
        vip:
          ip: 192.168.1.40

  - hostname: control-plane-03
    ipAddress: 192.168.1.43
    installDisk: /dev/sda
    controlPlane: true
    networkInterfaces:
      - interface: eth0
        dhcp: false
        addresses:
          - 192.168.1.43/24
        routes:
          - network: 0.0.0.0/0
            gateway: 192.168.1.1
        vip:
          ip: 192.168.1.40

  - hostname: worker-01
    ipAddress: 192.168.1.44
    installDisk: /dev/sda
    controlPlane: false
    schematic:
      customization:
        systemExtensions:
          officialExtensions:
            - siderolabs/i915
            - siderolabs/intel-ucode
    networkInterfaces:
      - interface: eth0
        dhcp: false
        addresses:
          - 192.168.1.44/24
        routes:
          - network: 0.0.0.0/0
            gateway: 192.168.1.1

controlPlane:
  patches:
    - "@./patches/all.yaml"
    - "@./patches/controlplane.yaml"

worker:
  patches:
    - "@./patches/all.yaml"
    - "@./patches/worker.yaml"
