# yamllint disable
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: vpn-gateway-vpnconfig
    namespace: networking
stringData:
    vpnConfigfile: ENC[AES256_GCM,data:5XT1N61rewylnCMFyQBsLmHKgLWY201ExDz9SRA3vLbvrGP5Ngw2csrsYVh5msF0GXLZdnnnIgYHkeKWGIlFcNvxJtV7hq1r76K5d/6LLh6TvGBxhcHH6gEd7dOIMUu+3JJVBZVDNoY5kQAEWsBianNgg4R99nxLJsUoTzUOwytxXkp05zFfMQ4Z/nx4xP1PvoyEfakPp0fz4DaK5MlMHjD2oEP51vNdIn0TGQf/8r7Pht8pG+TApnnE8ksXmENIyi/WgtMfH1GA8E2ZnLeJsV9N6r4PTPhOjJ9iuCJ5ibuc9Uq7yOtW6ySAAtbwFYDnPD5TtYrvaCX5+CxPK0RsT9SGedVslzjQzhyEQLIrIA==,iv:8//vn6J6S31SnLMhpl4usQcrtmXobOlanGtL8ue/Ga0=,tag:r7OBc1A0vms9joaZzxrdQg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-08-02T16:59:06Z"
    mac: ENC[AES256_GCM,data:jqbPBi5aUv21j+fWgYLr+J49xTYQXrdA4SOq0S/uNNYsuy6fEptO/9aVwSr0RJO/8vGpnZ+68oHKx2bOTE0aRZYu0hk9MMzIhiWuiDqu+LeOPz2XU5ExQ/COouhURXmSTkSLKz33O+CmUewdfCQeM8Re18kWIfv8e9BXMISfgiY=,iv:jr7+ZxYpiC+pahfO7us1MkKd9CXewrJvEXn0aOOnF1k=,tag:DygBODE8XZBewlue6Dmrbg==,type:str]
    pgp:
        - created_at: "2021-08-02T15:51:47Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA6+sJYMUUo72AQ/+IRH/N34nPJ2LyyN72ePbvbGEd8vF8+HD1X0qCH/upO1L
            Q/lskzcTqOjrvSBpWXep9/o4lonpKqQdbvS3V4UD0eRfcRLRUQDH2RjQAD7jVJrs
            ddTjdRlNpQIyJh4xNujBPjB+teWG9jDksz9YidrS1Ry0Wz5RUHcCC5970pf2OY+o
            wQymoy7UmKgzrT3N562yb0l4/ssye5MpC3BjT90u+wkn6IuAc1pOB//CQGcKijlY
            1BvoPeZQ+7TalRvMq07PROp93Js68pTLTh7jcZ+xDJeXE+vpp94VIHR0nhQnfO1i
            phlyMyP8Drt1aH386J5KmflslfwLWqUtcR7mzqOPGIa5rd4iKoaUW2btERtTNvzO
            vw7askViTLHYGlodIwsys71R6mMxClXhlZot5lhZN3XzR5LQck0fDYsXyNEZ+ND3
            yzcJIaROzqgyexuxiYbs2lRqObaOhI3woxqojcKRK4+Ai1tnirSXIQwxBI/7tx8t
            7lhpacamUQ/jtZUWBE6n/jzT3/kX1a0cIkKyCZEvJF+5/sthabXQcf9usYbQIDKK
            jiqn99QHzaBnBRnwcwywk2C0wp4svrLosmfbK6CtEOFC31sSHZ8dLp98RDIH4WQw
            MAyDTs1waz1cQ+9QWN0fPcd6oi14yeNUJYMLvk9c75dcCjNE1Y1jvn3WWoYuTC7U
            aAEJAhVgA6/jdebeTOh2AsaE9vlbA4PTUysKrzV7nv5zBul3yhLzRD4T1IqGSdh0
            tQpVZgHb8IqOGOmP7lg2FqWM/LU1XMcViAEQBoILXLmGziMIV+nJneR13a+mcglq
            3OTUjO6eDId9
            =/jQH
            -----END PGP MESSAGE-----
          fp: B84ADBF2B1CBFB4B1D7812175BECD066ABE785D1
        - created_at: "2021-08-02T15:51:47Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAyoigsyNyDu0AQ/+MwDEIXuSi5slvFBfOvE9zeC5z8wIkV4vgjLhmWWzUJ+T
            GjTnA+YOYEJUTrfeupgODbHcw4I09kDZQVmUbifkEcS1OKBP1tvOcZCyUPF6089O
            QELEhob6dLM4Ykme+33mpDUg7RSj2T9hPsrotqk8bE87Pl5d4RlN7TGMiXb14zCU
            OkJI1cYTY3lxWRGldicgch6+pBfgj6ZUzhdZexuR0LZhCeiIfOweSDw4/cm43pvX
            MEeWbEUoeEhUQtq1OIFIWlCRO++Jd7r/aeBLTmvk3ojclZJp+CU3aZ622UzWB7wV
            l+O9Tbu5OMhTUkqcMkUgchaMc3D+/70efcyLJsP8K60WCrO75ZbfWOxN8KLkkQkp
            6PrWbKRV6+asYvbWIwfNmQ0lA8+dp3JhTc4D8X6VuH64lDSsXRS24Kn/A8/a5htf
            DKR6fIlmBJ2rqFxsRh7FzivXr2tAozUJGzQg2AleGO5xv42/0ImCNWbC0QFQrYCu
            /lzWJWQlkwVeuSsMD5kklmvhMmqwbNy/jSk32pLleo+epj2mNckdATkw5R9OCVPx
            iHzL9ErCltwweAgOCFUSU7bU83YRaxS8yHqBC7QjAW0chcGlipzwHtD/0Uu3K1aC
            aBcwDutrwxSWmMKGhcxRUvZW2G1KopOecCGuhhhOQQRc4K1rkXzYFVmJOTox+2nU
            aAEJAhXOvYJDYhof3sGAEindjYLMFEuGDR9N60LAgMEgukI0VcbnjdggDZXr9VGW
            +Qi0g0R/3RzKxYI7Pc/goS2GQpi3KNiwNWKaSs4LOCpzSzgt4eP6WEjq4pLhIVKr
            WZrZ7ZLMCFKF
            =+nSl
            -----END PGP MESSAGE-----
          fp: 3C78B9F2882CA975AD035A0F2B7AF27738EEB3FE
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
