---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: loki
      version: 6.45.2
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    loki:
      image:
        repository: grafana/loki
        tag: 2.9.1
      auth_enabled: false
      storage:
        type: filesystem
      commonConfig:
        replication_factor: 1
      limits_config:
        retention_period: 7d
      rulerConfig:
        alertmanager_url: http://kube-prometheus-stack-alertmanager:9093
    write:
      replicas: 0
    read:
      replicas: 0
    backend:
      replicas: 0
    singleBinary:
      replicas: 1
      persistence:
        size: 10Gi
        storageClass: longhorn-fast-replicated
    test:
      enabled: false
    monitoring:
      selfMonitoring:
        enabled: false
      lokiCanary:
        enabled: false
