---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: teleport-config
  namespace: security
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn-fast-replicated