---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: teleport
  namespace: security
spec:
  interval: 5m
  chart:
    spec:
      chart: teleport-cluster
      version: 10.3.3 
      sourceRef:
        kind: HelmRepository
        name: teleport-charts
        namespace: flux-system
      interval: 1m
  values:
    clusterName: teleport.${SECRET_DOMAIN}
    persistence:
      enabled: true
      existingClaimName: "teleport-config"
    highAvailability:
      replicaCount: 3
      certManager:
        enabled: true
        issuerName: letsencrypt-prod
        issuerKind: ClusterIssuer