---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- plans
- github.com/rancher/system-upgrade-controller?ref=v0.9.1
images:
  - name: rancher/system-upgrade-controller
    newName: docker.io/rancher/system-upgrade-controller
    newTag: v0.9.1
patchesStrategicMerge:
  - ./system-upgrade-patches.yaml