---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mosquitto
  namespace: home-automation
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 1.3.0
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    image:
      repository: eclipse-mosquitto
      tag: 2.0.15
    
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: ${MOSQUITTO_LB}
        externalTrafficPolicy: Local

    env:
      TZ: "Europe/Helsinki"

    persistence:
      configinc:
        enabled: true
        existingClaim: mosquitto-config
      data:
        enabled: true
        existingClaim: mosquitto-data

    resources:
      requests:
        cpu: 15m
        memory: 64M
      limits:
        memory: 124M