---
apiVersion: v1
kind: Service
metadata:
  name: homelab-docs
  namespace: homelab-docs
spec:
  type: ClusterIP
  selector:
    app: homelab-docs
  ports:
    - name: http
      port: 80
      targetPort: http
