---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  interval: 5m
  chart:
    spec:
      chart: authentik
      version: 2025.6.3
      sourceRef:
        kind: HelmRepository
        name: authentik-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    authentik:
      # Token and password only valid for the first boot
      bootstrap_token: ${AUTHENTIK_BOOTSTRAP_TOKEN}
      bootstrap_password: ${AUTHENTIK_BOOTSTRAP_PASSWORD}
      secret_key: ${AUTHENTIK_SECRET_KEY}
      postgresql:
        password: ${AUTHENTIK_POSTGRES_PASSWORD}
      log_level: debug
    blueprints:
      configMaps:
        - authentik-blueprints
    server:
      ingress:
        enabled: true
        hosts:
          - authentik.${SECRET_DOMAIN}
        annotations:
          # Automatically generate TLS certificate
          kubernetes.io/tls-acme: "true"
          # Let external-dns manage cloudflare DNS records
          external-dns/is-public: "true"
        tls:
          - secretName: authentik-tls
            hosts:
              - authentik.${SECRET_DOMAIN}
    postgresql:
      enabled: true
      auth:
        password: ${AUTHENTIK_POSTGRES_PASSWORD}
    redis:
      enabled: true
