---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  interval: 5m
  chart:
    spec:
      chart: authentik
      version: 2025.6.3
      sourceRef:
        kind: HelmRepository
        name: authentik-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    authentik:
      # Token and password only valid for the first boot
      bootstrap_token: supersecrettoken
      bootstrap_password: supersecretpassword
      secret_key: "PleaseGenerateA50CharKey"
      postgresql:
        password: "ThisIsNotASecurePassword"
      log_level: debug
    server:
      ingress:
        enabled: true
        hosts:
          - authentik.${SECRET_DOMAIN}
        annotations:
          # Automatically generate TLS certificate
          kubernetes.io/tls-acme: "true"
          # Let external-dns manage cloudflare DNS records
          external-dns/is-public: "true"
        tls:
          - secretName: authentik-tls
            hosts:
              - authentik.${SECRET_DOMAIN}}
    postgresql:
      enabled: true
      auth:
        password: "ThisIsNotASecurePassword"
    redis:
      enabled: true
