---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: media
spec:
  chart:
    spec:
      chart: app-template
      version: 1.3.1
      sourceRef:
        kind: HelmRepository
        name: bjw-charts
        namespace: flux-system
  interval: 30m
  values:
    image:
      repository: ghcr.io/onedr0p/sonarr-develop
      tag: 4.0.0.373@sha256:7b9d997c25c562f2bf6a535a1dc8325570f33e1ecebc519e30cc5306b96d9467
    env:
      TZ: "Europe/Helsinki"
    service:
      main:
        ports:
          http:
            port: 8989
    ingress:
      main: 
        enabled: true
        annotations:
          # Use forward-auth middleware for authentication
          traefik.ingress.kubernetes.io/router.middlewares: "traefik-forward-auth@kubernetescrd"
          # Let external-dns manage cloudflare DNS records
          external-dns/is-public: "true"
        hosts:
        - host: sonarr.${SECRET_DOMAIN}
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - sonarr.${SECRET_DOMAIN}
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 65539
    persistence:
      config:
        enabled: true
        existingClaim: sonarr-config
      media:
        enabled: true
        mountPath: /data
        existingClaim: media-pvc-01
    resources:
      requests:
        cpu: 100m
        memory: 256M
      limits:
        memory: 1024M