---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki-stack
  namespace: monitoring
spec:
  chart:
    spec:
      chart: loki-stack
      version: 2.9.11
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: flux-system
  interval: 30m
  values:
    test_pod:
      enabled: true
      image: bats/bats:1.8.2
      pullPolicy: IfNotPresent

    loki:
      enabled: true
      datasource:
        jsonData: "{}"
        uid: ""

    promtail:
      enabled: true
      config:
        logLevel: info
        serverPort: 3101
        clients:
          - url: http://{{ .Release.Name }}:3100/loki/api/v1/push

    grafana:
      enabled: true
      image:
        tag: 8.3.5
      sidecar:
        datasources:
          label: ""
          labelValue: ""
          enabled: true
          maxLines: 1000

    prometheus:
      enabled: true
      url: http://{{ include "prometheus.fullname" .}}:{{ .Values.prometheus.server.service.servicePort }}{{ .Values.prometheus.server.prefixURL }}
      datasource:
        jsonData: "{}"
