---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: plex
      version: 6.0.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/plex
      tag: v1.22.3.4392-d7c624def
    env:
      TZ: "Europe/Helsinki"
    service:
      main:
        type: LoadBalancer
        externalIPs:
          - "${PLEX_LB}"
        externalTrafficPolicy: Local
        annotations:
          # https://doc.traefik.io/traefik/routing/providers/kubernetes-ingress/#communication-between-traefik-and-pods
          traefik.ingress.kubernetes.io/service.serversscheme: https
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "traefik"
          # Set to use default cluster-issuer
          kubernetes.io/tls-acme: "true"
          # Set only "websecure" endpoint to be forwarded
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          # Set to passthrough TLS to backend service
          traefik.ingress.kubernetes.io/router.tls: "true"
        hosts:
          - host: "plex.${SECRET_DOMAIN}"
            paths:
              - path: /
        tls:
          - secretName: plex-tls
            hosts:
              - "plex.${SECRET_DOMAIN}"
    hostnetwork: true
    persistence:
      config:
        enabled: true
        mountPath: /config
        existingClaim: plex-config
      media:
        enabled: true
        mountPath: /data
        existingClaim: media-pvc
      transcode:
        enabled: true
        storageClass: "longhorn-slow"
        type: emptyDir
        medium: Memory
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: OnRootMismatch
    resources:
      requests:
        gpu.intel.com/i915: 1
        cpu: 500m
        memory: 1000Mi
      limits:
        gpu.intel.com/i915: 1
        memory: 8000Mi
