apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces
  - volumes
  - cert-manager
  - longhorn-system
  - kube-system
  - minio-azure-gateway
  - networking
  - security
  - traefik