apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- authelia/ks.yaml
- cert-manager/ks.yaml
- external-dns/ks.yaml
- home-assistant/ks.yaml
# - lazylibrarian/ks.yaml
# - lidarr/ks.yaml
- longhorn/ks.yaml
- minio-gateway/ks.yaml
- mosquitto/ks.yaml
- node-feature-discovery/ks.yaml
- node-red/ks.yaml
# Disabled to reduce resource usage temporarily.
# - plex/ks.yaml
- podinfo/ks.yaml
# - prowlarr/ks.yaml
# - qbittorrent/ks.yaml
# - radarr/ks.yaml
# - sonarr/ks.yaml
# Disabled to reduce resource usage temporarily.
# - tailscale/ks.yaml
- traefik/ks.yaml
