---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: weave-charts
  namespace: flux-system
spec:
  interval: 30m
  url: https://helm.gitops.weave.works
  timeout: 2m
