image:
  repository: ghcr.io/home-operations/radarr
  tag: 6.0.0.10217

env:
  TZ: Europe/London
  RADARR__AUTH__METHOD: External
  RADARR__AUTH__REQUIRED: DisabledForLocalAddresses
  RADARR__LOG__LEVEL: info
service:
  main:
    ports:
      http:
        port: 7878

ingress:
  main:
    enabled: true
    ingressClassName: traefik
    annotations:
      kubernetes.io/tls-acme: "true"
      traefik.ingress.kubernetes.io/router.middlewares: "authentik-forward-auth@kubernetescrd"
    hosts:
      - host: radarr.homelab.arsenikki.casa
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: radarr-tls
        hosts:
          - radarr.homelab.arsenikki.casa

podSecurityContext:
  runAsUser: 568
  runAsGroup: 568
  fsGroup: 568
  fsGroupChangePolicy: "OnRootMismatch"
  supplementalGroups: [10000]

persistence:
  config:
    enabled: true
    existingClaim: radarr-config
  media:
    enabled: true
    mountPath: /data
    existingClaim: media-pvc

resources:
  requests:
    cpu: 100m
    memory: 256M
  limits:
    memory: 1024M
