---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-red
  namespace: home-automation
spec:
  interval: 5m
  chart:
    spec:
      chart: node-red
      version: 10.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 1m
  values:
    env:
      TZ: "Europe/Helsinki"
    service:
      main:
        ports:
          http:
            port: 1880
    ingress:
      main:
        enabled: false
        annotations:
          # Use Traefik for ingress
          kubernetes.io/ingress.class: "traefik"
          # Use authelia-forward-auth middleware for authentication
          traefik.ingress.kubernetes.io/router.middlewares: "traefik-forward-auth@kubernetescrd"
          # Use default cluster-issuer
          kubernetes.io/tls-acme: "true"
          # Only allow websecure endpoint
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          # Set to passthrough TLS to backend service
          traefik.ingress.kubernetes.io/router.tls: "true"
        hosts:
          - host: "nodered.${SECRET_DOMAIN}"
            paths:
              - path: /
        tls:
          - secretName: nodered-tls
            hosts:
              - "nodered.${SECRET_DOMAIN}"
    persistence:
      data:
        enabled: true
        existingClaim: node-red-data
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: OnRootMismatch
