apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-red
  namespace: home-automation
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.3.0
      sourceRef:
        kind: HelmRepository
        name: bjw-charts
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      replicas: 1
      strategy: RollingUpdate
    image:
      repository: nodered/node-red
      tag: 3.0.2
    env:
      TZ: "Europe/Helsinki"
    service:
      main:
        ports:
          http:
            port: 80
    ingress:
      main: 
        enabled: true
        annotations:
          # Use authelia-forward-auth middleware for authentication
          traefik.ingress.kubernetes.io/router.middlewares: "traefik-forward-auth@kubernetescrd"
        hosts:
        - host: nodered.${SECRET_DOMAIN}
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - nodered.${SECRET_DOMAIN}
    podSecurityContext:
      container:
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: "OnRootMismatch"
    persistence:
      data:
        enabled: true
        type: pvc
        existingClaim: node-red-data 
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        cpu: 1
        memory: 1000Mi