---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-red
  namespace: home-automation
spec:
  interval: 5m
  chart:
    spec:
      chart: node-red
      version: 9.0.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 1m
  values:
    env:
      TZ: "Europe/Helsinki"
    service:
      main:
        ports:
          http:
            port: 1880
    ingress:
      main:
        enabled: false
    persistence:
      data:
        enabled: true
        existingClaim: node-red-data
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: OnRootMismatch
