controller:
  replicas: 1
  strategy: RollingUpdate

image:
  repository: nodered/node-red
  tag: 4.0.8

env:
  TZ: "Europe/London"

service:
  main:
    ports:
      http:
        port: 1880

ingress:
  main:
    enabled: true
    annotations:
      kubernetes.io/tls-acme: "true"
      traefik.ingress.kubernetes.io/router.middlewares: "authentik-forward-auth@kubernetescrd"
    hosts:
      - host: nodered.homelab.arsenikki.casa
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: nodered-tls
        hosts:
          - nodered.homelab.arsenikki.casa

podSecurityContext:
  runAsUser: 568
  runAsGroup: 568
  fsGroup: 568
  fsGroupChangePolicy: "OnRootMismatch"

persistence:
  data:
    enabled: true
    type: pvc
    existingClaim: node-red-data

resources:
  requests:
    cpu: 10m
    memory: 100Mi
  limits:
    cpu: 1
    memory: 1000Mi
