server:
  ## The address to listen on.
  host: 0.0.0.0
  ## The port to listen on.
  port: 9091
log:
  ## Level of verbosity for logs: info, debug, trace.
  level: trace
  format: json
  keep_stdout: true

jwt_secret: verysecretsecret

authentication_backend:
  file:
    path: /config/users.yaml

storage:
  encryption_key: you_must_generate_a_random_string_of_more_than_twenty_chars_and_configure_this
  local:
    path: /config/db.sqlite3

totp:
  issuer: authelia.com
  period: 30
  skew: 1

# https://docs.authelia.com/configuration/access-control.html
access_control:
  default_policy: deny
  rules:
    # Rules applied to everyone
    - domain: auth.${SECRET_DOMAIN}
      policy: bypass
    - domain: "*.${SECRET_DOMAIN}"
      policy: one_factor
    - domain: "${SECRET_DOMAIN}"
      policy: one_factor

session:
  name: authelia_session
  secret: unsecure_session_secret
  expiration: 3600 # 1 hour
  inactivity: 300 # 5 minutes
  domain: ${SECRET_DOMAIN} # Should match whatever your root protected domain is

notifier:
  filesystem:
    filename: /config/notifications.txt