server:
  ## The address to listen on.
  host: 0.0.0.0
  ## The port to listen on.
  port: 9091
log:
  ## Level of verbosity for logs: info, debug, trace.
  level: info

jwt_secret: ${SECRET_AUTHELIA_JWT_TOKEN}

authentication_backend:
  file:
    path: /config/users.yaml

storage:
  encryption_key: ${SECRET_AUTHELIA_ENCRYPTION_KEY}
  postgres:
    host: authelia-postgresql
    port: 5432
    database: authelia
    schema: public
    username: authelia
    password: "${SECRET_AUTHELIA_STORAGE_PASSWORD}"

totp:
  issuer: authelia.com
  period: 30
  skew: 1

# https://docs.authelia.com/configuration/access-control.html
access_control:
  default_policy: deny
  rules:
    # Rules applied to everyone
    - domain: auth.${SECRET_DOMAIN}
      policy: bypass
    - domain: "*.${SECRET_DOMAIN}"
      policy: one_factor
    - domain: "${SECRET_DOMAIN}"
      policy: one_factor

session:
  domain: ${SECRET_DOMAIN}
  secret: ${SECRET_AUTHELIA_SESSION_SECRET}
  redis:
    host: authelia-redis-master
    username: authelia
    password: ${SECRET_AUTHELIA_REDIS_PASSWORD}
    port: 6379

notifier:
  filesystem:
    filename: /config/notifications.txt