apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: security
configMapGenerator:
  - name: authelia-users
    files:
      - users.yaml
  - name: authelia-config
    files:
      - configuration.yaml
generatorOptions:
  disableNameSuffixHash: true