---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: media
spec:
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-charts
        namespace: flux-system
  interval: 30m
  values:
    image:
      repository: ghcr.io/onedr0p/qbittorrent
      tag: 4.5.5
    env:
      TZ: "Europe/London"
      QBITTORRENT__PORT: 80
      QBITTORRENT__BT_PORT: 50413
    sidecars:
      gluetun:
        image: qmcgaw/gluetun:v3.32
        env:
        - name: VPN_SERVICE_PROVIDER
          value: private internet access
        - name: SERVER_REGIONS
          value: Netherlands
        - name: OPENVPN_USER
          value: ${PIA_USERNAME}
        - name: OPENVPN_PASSWORD
          value: ${PIA_PASSWORD}
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
    hostname: qbittorrent
    service:
      main:
        ports:
          http:
            port: 80
      bittorrent:
        enabled: true
        type: LoadBalancer
        ports:
          bittorrent:
            enabled: true
            port: 50413
            protocol: TCP
            targetPort: 50413
        externalTrafficPolicy: Local
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false
    ingress:
      main:
        enabled: true
        annotations:
          # Use forward-auth middleware for authentication
          traefik.ingress.kubernetes.io/router.middlewares: "traefik-forward-auth@kubernetescrd"
          # Let external-dns manage cloudflare DNS records
          external-dns/is-public: "true"
        hosts:
        - host: qbittorrent.${SECRET_DOMAIN}
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - qbittorrent.${SECRET_DOMAIN}
    persistence:
      config:
        enabled: true
        existingClaim: qbittorrent-config
      media:
        enabled: true
        mountPath: /data
        existingClaim: media-pvc
    securityContext:
      runAsUser: 568
      runAsGroup: 568
    podSecurityContext:
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups: [10000]
    resources:
      requests:
        cpu: 100m
        memory: 128M
      limits:
        memory: 1500M
