---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cast-sponsor-skip
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-charts
        namespace: flux-system
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/gabe565/castsponsorskip
              tag: 0.7.2
            env:
              TZ: "Europe/London"
        strategy: RollingUpdate
        pod:
          hostNetwork: true
          dnsPolicy: ClusterFirstWithHostNet
    service:
      main:
        enabled: false
