---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prowlarr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: prowlarr
      version: 4.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/prowlarr
      tag: v0.1.0.421
    env:
      TZ: "Europe/Helsinki"
    ingress:
      main:
        enabled: true
        annotations:
          # Use Traefik for ingress
          kubernetes.io/ingress.class: "traefik"
          # Use authelia-forward-auth middleware for authentication
          traefik.ingress.kubernetes.io/router.middlewares: "security-forwardauth-authelia@kubernetescrd"
          # Only allow websecure endpoint
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          # Let external-dns manage cloudflare DNS records
          external-dns/is-public: "true"
        hosts:
        - host: "prowlarr.${SECRET_DOMAIN}"
          paths:
          - path: /
        tls:
        - hosts:
          - "prowlarr.${SECRET_DOMAIN}"
    persistence:
      config:
        enabled: true
        existingClaim: prowlarr-config
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: OnRootMismatch
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 500Mi
