apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: security
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.3.0
      sourceRef:
        kind: HelmRepository
        name: bjw-charts
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      replicas: 1
      strategy: RollingUpdate
    image:
      repository: vaultwarden/server
      tag: 1.25.2
    env:
      TZ: "Europe/Helsinki"
      DATA_FOLDER: "config"
      SIGNUPS_ALLOWED: false
      WEBSOCKET_ENABLED: true
      WEBSOCKET_ADDRESS: 0.0.0.0
      WEBSOCKET_PORT: 3012
      DOMAIN: https://vault.${SECRET_DOMAIN}
      ADMIN_TOKEN: ${SECRET_VAULTWARDEN_ADMIN_TOKEN}
      DATABASE_URL: postgresql://${SECRET_VAULTWARDEN_PSQL_USERNAME}:${SECRET_VAULTWARDEN_PSQL_PASSWORD}@vaultwarden-postgresql:5432/vaultwarden
    service:
      main:
        ports:
          http:
            port: 80
    ingress:
      main: 
        enabled: true
        annotations:
          # Let external-dns manage cloudflare DNS records
          external-dns/is-public: "true"
        hosts:
        - host: vault.${SECRET_DOMAIN}
          paths:
          - path: /
            pathType: Prefix
          - path: /notifications/hub/negotiate
            pathType: Prefix
            service:
              port: 80
          - path: /notifications/hub
            pathType: Prefix
            service:
              port: 3012
        tls:
        - hosts:
          - vault.${SECRET_DOMAIN}
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
    persistence:
      config:
        enabled: true
        type: pvc
        existingClaim: vaultwarden-config
    initContainers:
      update-config-ownership:
        image: busybox:1.36.0
        command: ["sh", "-c", "chown -R 568:568 /config"]
        volumeMounts:
          - name: config
            mountPath: /config
        securityContext:
          runAsUser: 0
      update-config-permission:
        image: busybox:1.36.0
        command: ["sh", "-c", "chmod -R 770 /config"]
        volumeMounts:
          - name: config
            mountPath: /config
        securityContext:
          runAsUser: 0
    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        cpu: 1
        memory: 1000Mi    
