---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vaultwarden-postgresql
  namespace: security
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: postgresql
      version: 12.1.14
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  values:
    primary:
      persistence:
        enabled: true
        existingClaim: "vaultwarden-psql"
      podSecurityContext:
        enabled: true
        fsGroup: 568
      containerSecurityContext:
        enabled: true
        runAsUser: 568
    auth:
      username: "${SECRET_VAULTWARDEN_PSQL_USERNAME}"
      database: vaultwarden
      password: "${SECRET_VAULTWARDEN_PSQL_PASSWORD}"
      postgresPassword: "${SECRET_VAULTWARDEN_PSQL_PASSWORD}"
