---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik-forward-auth
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: traefik-forward-auth
      version: 1.0.10
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    authHost: "auth.${SECRET_DOMAIN}"
    cookie:
      domain: "${SECRET_DOMAIN}"
    providers:
      google:
        # providers.google.enabled -- Enable the google provider
        enabled: true
        # providers.google.clientId -- Client ID
        clientId: "${SECRET_TRAEFIK_GOOGLE_ID}"
        # providers.google.clientSecret -- Client Secret
        clientSecret: "${SECRET_TRAEFIK_GOOGLE_SECRET}"
    restrictions:
      whitelist: "${SECRET_AUTH_WHITELIST_EMAILS}"
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "traefik"
        # Set to use default cluster-issuer
        kubernetes.io/tls-acme: "true"
        # Set only "websecure" endpoint to be forwarded
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        # Set to passthrough TLS to backend service
        traefik.ingress.kubernetes.io/router.tls: "true"
      hosts:
        - host: "auth.${SECRET_DOMAIN}"
          paths:
            - /
      tls:
        - secretName: traefik-forward-auth-tls
          hosts:
            - "auth.${SECRET_DOMAIN}"
    middleware:
      enabled: true
    logging:
      level: "trace"
