---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: ytdl-sub-app
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-charts
        namespace: flux-system
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/jmbannon/ytdl-sub
              tag: ubuntu-2024.06.06
              pullPolicy: IfNotPresent
            env:
              TZ: "Europe/London"
              PGUID: 568
              PGID: 568
              UMASK_SET: 022
            resources:
              requests:
                cpu: 15m
                memory: 250M
              limits:
                memory: 1G
    service:
      main:
        enabled: false
    persistence:
      config:
        enabled: true
        type: configMap
        name: ytdl-config
        globalMounts:
          - path: /config/config.yaml
            subPath: config.yaml
            readOnly: true
      subscription:
        enabled: true
        type: configMap
        name: ytdl-subscription
        globalMounts:
          - path: /config/subscription.yaml
            subPath: subscription.yaml
            readOnly: true
      media:
        enabled: true
        globalMounts:
          - path: /data/workouts
            subPath: workouts
            readOnly: false
        existingClaim: media-pvc
      tmp:
        enabled: true
        type: emptyDir
        globalMounts:
          - path: /data/downloads/ytdl
            subPath: ytdl
            readOnly: false
    defaultPodOptions:
      enableServiceLinks: true
      securityContext:
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: "OnRootMismatch"
        supplementalGroups:
          - 65539
