---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: teleport-kube-agent-data
  namespace: teleport
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn-fast-replicated
