---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: teleport-kube-agent
  namespace: teleport
spec:
  chart:
    spec:
      chart: teleport-kube-agent
      version: 15.4.22
      sourceRef:
        kind: HelmRepository
        name: teleport-charts
        namespace: flux-system
  interval: 30m
  values:
    log:
      level: DEBUG
    roles: kube,app,discovery
    insecureSkipProxyTLSVerify: true
    proxyAddr: teleport.${SECRET_DOMAIN}:443
    joinParams:
      method: kubernetes
      # Following must match the name of the token in token.yaml
      tokenName: "kubernetes-join-token"
    kubeClusterName: home-cluster
    apps:
      - name: home-assistant
        uri: https://homeassistant.${SECRET_DOMAIN}
