---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: teleport-kube-agent
  namespace: teleport
spec:
  chart:
    spec:
      chart: teleport-kube-agent
      version: 14.3.3
      sourceRef:
        kind: HelmRepository
        name: teleport-charts
        namespace: flux-system
  interval: 30m
  values:
    roles: kube,app,discovery 
    proxyAddr: 
    authToken: ${SECRET_TELEPORT_AGENT_AUTH_TOKEN}
    kubeClusterName: home-cluster
    apps:
      - name: home-assistant
        uri: https://home.arsenikki.xyz