---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: qbittorrent
      version: 11.3.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/qbittorrent
      tag: v4.3.5
      pullPolicy: IfNotPresent
    hostname: qbittorrent
    env:
      # Our qBittorrent image has a feature that can wait for the VPN to be connected before actually starting the application.
      # It does this by checking the contents of a file /shared/vpnstatus to contain the string 'connected'.
      WAIT_FOR_VPN: "false"
    podAnnotations:
      setGateway: "true"
    settings:
      automaticPortSetup: true
    persistence:
      config:
        enabled: true
        type: emptyDir
        mountPath: /config
      # This should be enabled so that both the qBittorrent and Wireguard container have access to a shared volume mounted to /shared.
      # It will be used to communicate between the two containers.
      shared:
        enabled: true
        type: emptyDir
        mountPath: /shared
      media:
        enabled: true
        existingClaim: media-pvc
    service:
      bittorrent:
        enabled: true
        type: ClusterIP
        ports:
          bittorrent:
            enabled: true
            port: 18289
            protocol: TCP
            targetPort: 18289
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "traefik"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-traefik-forward-auth@kubernetescrd"
        hosts:
          - host: "qbittorrent.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "qbittorrent.${SECRET_DOMAIN}"
    podSecurityContext:
      supplementalGroups:
        - 65536
    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 6000Mi
