---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: sonarr
      version: 11.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/sonarr
      tag: v3.0.6.1196
    env:
      TZ: "Europe/Helsinki"
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "traefik"
        kubernetes.io/tls-acme: "true"
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: "sonarr.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: sonarr-cert
          hosts:
            - "sonarr.${SECRET_DOMAIN}"
    persistence:
      config:
        enabled: true
        existingClaim: sonarr-config
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: OnRootMismatch
    #    additionalVolumeMounts:
    #      - name: media-rocinante
    #        mountPath: "/media-rocinante"
    #      - name: media-serenity
    #        mountPath: "/media-serenity"
    #    additionalVolumes:
    #      - name: media-rocinante
    #        persistentVolumeClaim:
    #          claimName: nfs-media-rocinante-pvc
    #      - name: media-serenity
    #        persistentVolumeClaim:
    #          claimName: nfs-media-serenity-pvc
    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 1500Mi
