apiVersion: v1
kind: ConfigMap
metadata:
  name: meshcentral-config
  namespace: meshcentral
data:
  config.json: |
    {
      "settings": {
        "port": 8080
      },
      "domains": {
        "": {
          "userQuota": 1048576,
          "meshQuota": 248576,
          "newAccounts": 0
        }
      }
    }
