---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-3.3.2/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app meshcentral
  namespace: meshcentral
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 3.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-charts
        namespace: flux-system
  values:
    controllers:
      *app :
        replicas: 1
        type: statefulset
        containers:
          *app :
            image:
              repository: ghcr.io/ylianst/meshcentral
              tag: 1.1.53
            env:
              TZ: Europe/London
              NODE_ENV: production
              HOSTNAME: &host mesh.${SECRET_DOMAIN}
              ALLOW_NEW_ACCOUNTS: "false"
            resources:
              requests:
                cpu: 100m
              limits:
                memory: 2Gi

    persistence:
      config:
        type: configMap
        name: meshcentral-config
        advancedMounts:
          *app :
            *app :
              - path: /opt/meshcentral/meshcentral-data/config.json
                subPath: config.json
      data:
        existingClaim: meshcentral-data
        globalMounts:
          - path: /root
            subPath: rootdir
          - path: /opt/meshcentral/meshcentral-data
            subPath: data
          - path: /opt/meshcentral/meshcentral-files
            subPath: userfiles
          - path: /opt/meshcentral/meshcentral-backups
            subPath: backups

    service:
      main:
        controller: *app
        type: ClusterIP
        ports:
          http:
            port: 8080

    ingress:
      main:
        className: traefik
        annotations:
          # Automatically generate TLS certificate
          kubernetes.io/tls-acme: "true"
        hosts:
          - host: *host
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
        tls:
          - hosts:
              - *host
            secretName: meshcentral-tls
