---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: meshcentral-data
  namespace: meshcentral
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn-fast-replicated
