---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authelia-postgres-data
  namespace: authelia
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn-fast-replicated
