---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: authelia-postgresql
  namespace: authelia
spec:
  interval: 5m
  chart:
    spec:
      chart: postgresql
      version: 15.5.38
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  values:
    primary:
      persistence:
        enabled: true
        existingClaim: "authelia-postgres-data"
    auth:
      username: authelia
      database: authelia
      password: ${SECRET_AUTHELIA_POSTGRES_PASSWORD}
      postgresPassword: ${SECRET_AUTHELIA_STORAGE_PASSWORD}
