---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: authelia-redis
  namespace: authelia
spec:
  interval: 5m
  chart:
    spec:
      chart: redis
      version: 17.7.1
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  values:
    master:
      persistence:
        enabled: true
        existingClaim: "authelia-redis-data"
    replica:
      replicaCount: 0
    metrics:
      enabled: true
    auth:
      enabled: true
      password: ${SECRET_AUTHELIA_REDIS_PASSWORD}
