---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: core-sync
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./core
  dependsOn:
    - name: flux-sync
  prune: false
  sourceRef:
    kind: OCIRepository
    name: kuberseni-gitops-source
    namespace: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substitute: {}
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
      - kind: Secret
        name: cluster-secrets
