---
server:
  ## The address to listen on.
  host: 0.0.0.0
  ## The port to listen on.
  port: 9091
log:
  ## Level of verbosity for logs: info, debug, trace.
  level: info

identity_validation:
  reset_password:
    jwt_secret: ${SECRET_AUTHELIA_JWT_TOKEN}

authentication_backend:
  file:
    path: /config/users.yaml

storage:
  encryption_key: ${SECRET_AUTHELIA_ENCRYPTION_KEY}
  postgres:
    host: authelia-postgresql
    port: 5432
    database: authelia
    schema: public
    username: authelia
    password: ${SECRET_AUTHELIA_POSTGRES_PASSWORD}

totp:
  disable: false
  issuer: "USERNAME.com"
  algorithm: "sha1"
  digits: 6
  period: 30
  skew: 1
  secret_size: 32
  allowed_algorithms:
    - "SHA1"
  allowed_digits:
    - 6
  allowed_periods:
    - 30
  disable_reuse_security_policy: true

# https://docs.authelia.com/configuration/access-control.html
access_control:
  default_policy: deny
  rules:
    # Rules applied to everyone
    - domain: auth.${SECRET_DOMAIN}
      policy: bypass
    - domain: "*.${SECRET_DOMAIN}"
      policy: one_factor
    - domain: "${SECRET_DOMAIN}"
      policy: one_factor

session:
  domain: ${SECRET_DOMAIN}
  secret: ${SECRET_AUTHELIA_SESSION_SECRET}
  redis:
    host: authelia-redis-master
    password: ${SECRET_AUTHELIA_REDIS_PASSWORD}
    port: 6379

notifier:
  filesystem:
    filename: /config/notifications.txt
