---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authelia
  namespace: authelia
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-charts
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      replicas: 1
      strategy: RollingUpdate
    image:
      repository: ghcr.io/authelia/authelia
      tag: 4.37.5
    # Set config path explicitly as otherwise default filepath extension is '.yml'. Yuck!
    args: ["--config", "/config/configuration.yaml"]
    enableServiceLinks: false
    service:
      main:
        ports:
          http:
            port: 80
    ingress:
      main:
        enabled: true
        annotations:
          # Automatically generate TLS certificate
          kubernetes.io/tls-acme: "true"
          # Let external-dns manage cloudflare DNS records
          external-dns/is-public: "true"
        hosts:
        - host: auth.${SECRET_DOMAIN}
          paths:
          - path: /
            pathType: Prefix
        tls:
        - secretName: authelia-tls
          hosts:
          - auth.${SECRET_DOMAIN}
    podSecurityContext:
      container:
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: "OnRootMismatch"
    persistence:
      config:
        enabled: true
        type: configMap
        name: authelia-config
        subPath: configuration.yaml
        mountPath: /config/configuration.yaml
        readOnly: false
      users:
        enabled: true
        type: configMap
        name: authelia-users
        subPath: users.yaml
        mountPath: /config/users.yaml
        readOnly: false
