---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: authelia
resources:
  - persistence
  - helm-release.yaml
  - namespace.yaml
patches:
  - patch: |-
      apiVersion: helm.toolkit.fluxcd.io/v2beta2
      kind: HelmRelease
      metadata:
        name: not-used
      spec:
        values:
          env:
            AUTHELIA_AUTHENTICATION_BACKEND_PASSWORD_RESET_DISABLE: "true"
            AUTHELIA_DEFAULT_REDIRECTION_URL: https://auth.${SECRET_DOMAIN}
            AUTHELIA_DUO_API_DISABLE: "true"
            AUTHELIA_SERVER_DISABLE_HEALTHCHECK: "true"
            AUTHELIA_SERVER_PORT: 80
            AUTHELIA_SESSION_DOMAIN: ${SECRET_DOMAIN}
            AUTHELIA_THEME: grey
            AUTHELIA_TOTP_ISSUER: authelia.com
            AUTHELIA_WEBAUTHN_DISABLE: "true"
    target:
      kind: HelmRelease
      name: authelia
configMapGenerator:
  - name: authelia-config
    files:
      - ./config/configuration.yaml
  - name: authelia-users
    files:
      - ./config/users.yaml
generatorOptions:
  disableNameSuffixHash: true
