---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home-automation
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-charts
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      type: statefulset
    image:
      repository: ghcr.io/home-assistant/home-assistant
      tag: 2024.12.5
    env:
      TZ: "Europe/London"
    # Temporary workaround for mDNS discovery used by Homekit
    hostNetwork: true
    service:
      main:
        ports:
          http:
            port: 8123
          homekit:
            port: 21063
    ingress:
      main:
        enabled: true
        annotations:
          # Automatically generate TLS certificate
          kubernetes.io/tls-acme: "true"
        hosts:
          - host: homeassistant.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: home-assistant-tls
            hosts:
              - homeassistant.${SECRET_DOMAIN}
    ### Run as root for now
    # podSecurityContext:
    #   runAsUser: 568
    #   runAsGroup: 568
    #   fsGroup: 568
    #   fsGroupChangePolicy: "OnRootMismatch"
    persistence:
      config:
        enabled: true
        type: pvc
        existingClaim: home-assistant-config
    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        memory: 2000Mi
    addons:
      codeserver:
        enabled: true
        image:
          repository: ghcr.io/coder/code-server
          tag: 4.95.3
          pullPolicy: IfNotPresent
        env:
          TZ: "Europe/London"
        args:
          - --auth
          - "none"
          - --user-data-dir
          - "/config/.vscode"
          - --extensions-dir
          - "/config/.vscode"
        volumeMounts:
          - name: config
            mountPath: /config
        ingress:
          enabled: true
          annotations:
            # Automatically generate TLS certificate
            kubernetes.io/tls-acme: "true"
            # Use forward-auth middleware for authentication
            traefik.ingress.kubernetes.io/router.middlewares: "authentik-forward-auth@kubernetescrd"
            # Let external-dns manage cloudflare DNS records
            external-dns/is-public: "true"
          hosts:
            - host: "code.homeassistant.${SECRET_DOMAIN}"
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - secretName: home-assistant-vscode-tls
              hosts:
                - "code.homeassistant.${SECRET_DOMAIN}"
