---
apiVersion: v1
kind: ConfigMap
metadata:
  name: untappi-go-config
  namespace: untappi-go
  labels:
    app.kubernetes.io/part-of: untappi-go
data:
  NATS_URL: "nats://nats:4222"
  UNTAPPD_BASE_URL: "https://api.untappd.com/v4"
  UNTAPPD_HOURLY_BUDGET: "90"
  HTTP_ADDR: ":8080"
