---
apiVersion: v1
kind: Secret
metadata:
  name: oauth2-proxy-helm-values
  namespace: auth
type: Opaque
stringData:
  values.yaml: |-
    config:
      clientSecret: "${SECRET_OAUTH2_PROXY_SECRET}"
      cookieSecret: "${SECRET_OAUTH2_PROXY_COOKIE_SECRET}"
      clientID: "Ov23lirEtPS4fGSRlpXZ"
