---
# 1Password item: "renovate-ce" (in the kuberseni vault, via the `onepassword`
# ClusterSecretStore) with fields:
#   license_key             — Mend Renovate CE license key. The free 10-repo key
#                             is public (see the chart values.yaml comment):
#                             eyJsaW1pdCI6IjEwIn0=.30440220457941b71ea8eb345c729031718b692169f0ce2cf020095fd328812f4d7d5bc1022022648d1a29e71d486f89f27bdc8754dfd6df0ddda64a23155000a61a105da2a1
#                             (or register a free unrestricted key at mend.io/renovate-community).
#   github_app_id           — numeric App ID of the Renovate GitHub App you create.
#   github_app_private_key  — the App's private key (full multi-line PEM).
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate-ce
  namespace: renovate
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: renovate-ce
    creationPolicy: Owner
  data:
    - secretKey: mendRnvLicenseKey
      remoteRef:
        key: "renovate-ce"
        property: license_key
    - secretKey: mendRnvGithubAppId
      remoteRef:
        key: "renovate-ce"
        property: github_app_id
    - secretKey: mendRnvGithubAppKey
      remoteRef:
        key: "renovate-ce"
        property: github_app_private_key
