---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: readarr-config
  namespace: books
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn-fast-replicated
