---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: readarr
  namespace: books
spec:
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-charts
        namespace: flux-system
  interval: 30m
  values:
    image:
      repository: ghcr.io/onedr0p/readarr-develop
      tag: 0.3.5.2217
    env:
      TZ: "Europe/London"
    service:
      main:
        ports:
          http:
            port: 8787
    ingress:
      main:
        enabled: true
        ingressClassName: traefik
        annotations:
          # Automatically generate TLS certificate
          kubernetes.io/tls-acme: "true"
          # Use forward-auth middleware for authentication
          traefik.ingress.kubernetes.io/router.middlewares: "traefik-forward-auth@kubernetescrd"
          # Let external-dns manage cloudflare DNS records
          external-dns/is-public: "true"
        hosts:
        - host: readarr.${SECRET_DOMAIN}
          paths:
          - path: /
            pathType: Prefix
        tls:
        - secretName: readarr-tls
          hosts:
          - readarr.${SECRET_DOMAIN}
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups: [10000]
    persistence:
      config:
        enabled: true
        existingClaim: readarr-config
      books:
        enabled: true
        mountPath: /data
        existingClaim: books-pvc
    resources:
      requests:
        cpu: 100m
        memory: 256M
      limits:
        memory: 512M
