---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: paperless-ngx
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    defaultPodOptions:
      securityContext:
        fsGroup: 65539
        fsGroupChangePolicy: OnRootMismatch

    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/paperless-ngx/paperless-ngx
              tag: 2.4.3
            env:
              PAPERLESS_CONSUMER_POLLING: 5
              PAPERLESS_OCR_LANGUAGE: eng+fin
              PAPERLESS_PORT: 8000
              PAPERLESS_TIME_ZONE: Europe/London
              PAPERLESS_URL: "https://paperless.${SECRET_DOMAIN}"
              PAPERLESS_REDIS: redis://redis.database.svc.cluster.local
              PAPERLESS_ENABLE_HTTP_REMOTE_USER: "true"
            envFrom:
              - secretRef:
                  name: paperless-ngx-secret
    service:
      main:
        ports:
          http:
            port: 8000
    ingress:
      main:
        enabled: true
        className: traefik
        annotations:
          # Automatically generate TLS certificate
          kubernetes.io/tls-acme: "true"
          # Use forward-auth middleware for authentication
          traefik.ingress.kubernetes.io/router.middlewares: "traefik-forward-auth@kubernetescrd"
        hosts:
          - host: "paperless.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - "paperless.${SECRET_DOMAIN}"
    persistence:
      data:
        enabled: true
        existingClaim: paperless-ngx
        globalMounts:
          - subPath: data
            path: /usr/src/paperless/data
          - subPath: media
            path: /usr/src/paperless/media
      export:
        enabled: true
        type: nfs
        server: ${TRUENAS_IP_ADDRESS}
        path: /apps/paperless/export
        globalMounts:
          - path: /usr/src/paperless/export
      consume:
        enabled: true
        type: nfs
        server: ${TRUENAS_IP_ADDRESS}
        path: /apps/paperless/consume
        globalMounts:
          - path: /usr/src/paperless/consume
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: paperless-ngx-redis
spec:
  interval: 5m
  chart:
    spec:
      chart: redis
      version: 18.12.1
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  values:
    architecture: standalone
    master:
      persistence:
        enabled: true
        existingClaim: paperless-ngx-redis
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    auth:
      enabled: false
