---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: paperless-ngx
  namespace: paperless-ngx
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-charts
        namespace: flux-system
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/paperless-ngx/paperless-ngx
              tag: 2.7.2
            env:
              PAPERLESS_CONSUMER_POLLING: 5
              PAPERLESS_CONSUMER_RECURSIVE: "true"
              PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS: "true"
              PAPERLESS_DATA_DIR: /library/data
              PAPERLESS_MEDIA_ROOT: /library/media
              PAPERLESS_CONSUMPTION_DIR: /library/consume
              PAPERLESS_EXPORT_DIR: /library/export
              PAPERLESS_ENABLE_HTTP_REMOTE_USER: "true"
              PAPERLESS_OCR_LANGUAGE: eng
              PAPERLESS_PORT: 8000
              PAPERLESS_TIME_ZONE: Europe/London
              PAPERLESS_URL: "https://paperless.${SECRET_DOMAIN}"
              PAPERLESS_REDIS: redis://paperless-ngx-redis-master:6379
            securityContext:
              runAsUser: 1000
              runAsGroup: 1000
              fsgroup: 1000
              fsGroupChangePolicy: "OnRootMismatch"
    service:
      main:
        ports:
          http:
            port: 8000
    ingress:
      main:
        enabled: true
        className: traefik
        annotations:
          # Automatically generate TLS certificate
          kubernetes.io/tls-acme: "true"
          # Use forward-auth middleware for authentication
          traefik.ingress.kubernetes.io/router.middlewares: "traefik-forward-auth@kubernetescrd"
        hosts:
          - host: "paperless.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - "paperless.${SECRET_DOMAIN}"
    persistence:
      library:
        enabled: true
        existingClaim: paperless-ngx-nfs
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: paperless-ngx-redis
  namespace: paperless-ngx
spec:
  interval: 5m
  chart:
    spec:
      chart: redis
      version: 18.12.1
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  values:
    architecture: standalone
    master:
      persistence:
        enabled: true
        existingClaim: paperless-ngx-redis
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    auth:
      enabled: false
