---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-ngx
  namespace: paperless-ngx
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn-fast-replicated
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-ngx-redis
  namespace: paperless-ngx
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn-fast-replicated
