---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: paperless-ngx-nfs
spec:
  storageClassName: paperless-ngx-nfs
  capacity:
    storage: 1Mi # Size does not matter
  accessModes: ["ReadWriteMany"]
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${TRUENAS_IP_ADDRESS}
    path: /mnt/main/apps/paperless-ngx
  # Note: The first two options are strictly for NFSv4.2
  mountOptions: ["nfsvers=4.2", "nconnect=8", "hard", "noatime"]
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-ngx-nfs
  namespace: paperless-ngx
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: paperless-ngx-nfs
  resources:
    requests:
      storage: 1Mi # Size does not matter
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-ngx-redis
  namespace: paperless-ngx
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn-fast-replicated
