---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://helm.traefik.io/traefik
      chart: traefik
      version: 10.0.0
      sourceRef:
        kind: HelmRepository
        name: traefik-charts
        namespace: flux-system
  values:
    deployment:
      kind: Deployment
      replicas: 1
    service:
      enabled: true
      type: LoadBalancer
      spec:
        loadBalancerIP: "${TRAEFIK_LB}"
    ports:
      web:
        port: 80
      websecure:
        port: 443
    # Enable both CRD and annotation methods of defining ingress
    providers:
      kubernetesCRD:
        enabled: true
      kubernetesIngress:
        enabled: true
        # Needed, as otherwise ingresses don't get IPs automatically
        publishedService:
          enabled: true
    logs:
      general:
        level: "DEBUG"
    pilot:
      enabled: true
      token: "${SECRET_TRAEFIK_PILOT_TOKEN}"
    securityContext:
      capabilities:
        drop: [ALL]
        add: [NET_BIND_SERVICE]
      readOnlyRootFilesystem: true
      runAsGroup: 0
      runAsNonRoot: false
      runAsUser: 0
    resources:
      requests:
        memory: 100Mi
        cpu: 500m
      limits:
        memory: 500Mi
