---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  releaseName: longhorn
  interval: 5m
  chart:
    spec:
      chart: longhorn
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: longhorn-charts
        namespace: flux-system
      interval: 5m
  values:
    persistence:
      defaultClassReplicaCount: 3
    defaultSettings:
      defaultReplicaCount: 3
      backupTarget: s3://${LONGHORN_BACKUP_BUCKET}@lol/
      backupTargetCredentialSecret: minio-aws-secret
      backupstorePollInterval: 0
      createDefaultDiskLabeledNodes: true
      storageOverProvisioningPercentage: 100
      storageMinimalAvailablePercentage: 10
      guaranteedEngineManagerCPU: 20
      guaranteedReplicaManagerCPU: 20
      defaultDataPath: /var/lib/longhorn
      concurrentAutomaticEngineUpgradePerNodeLimit: 3
      defaultLonghornStaticStorageClass: longhorn-fast-replicated
      nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
