---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: pve-exporter
  namespace: monitoring
spec:
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-charts
        namespace: flux-system
  interval: 30m
  values:
    image:
      repository: prompve/prometheus-pve-exporter
      tag: 2.3.1
    env:
      TZ: "Europe/London"
      PVE_USER: "${SECRET_PROXMOX_METRICS_USERNAME}"
      PVE_PASSWORD: "${SECRET_PROXMOX_METRICS_PASSWORD}"
      PVE_VERIFY_SSL: false
    service:
      main:
        ports:
          http:
            port: 9221
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
    resources:
      requests:
        cpu: 15m
        memory: 30Mi
      limits:
        memory: 50Mi
