---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pve-exporter
  namespace: monitoring
spec:
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-charts
        namespace: flux-system
  interval: 30m
  values:
    image:
      repository: prompve/prometheus-pve-exporter
      tag: 2.3.1
    env:
      TZ: "Europe/London"
      PVE_USER: "metrics-exporter@pve"
      PVE_TOKEN_NAME: "monitoring"
      PVE_TOKEN_VALUE: "0aa5b117-8409-461c-b407-a0c9b6ddbcc1"
      PVE_VERIFY_SSL: false
    service:
      main:
        ports:
          http:
            port: 9221
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups: [10000]
    resources:
      requests:
        cpu: 15m
        memory: 30Mi
      limits:
        memory: 50Mi