---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: kuberseni
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Kuberseni home cluster
  sourceRepos:
    - https://github.com/Arsenikki/kuberseni-gitops
    - https://github.com/Arsenikki/claudtainer-homelab
    - https://github.com/Arsenikki/jeeves
    - https://helm.cilium.io
    - https://charts.jetstack.io
    - https://charts.longhorn.io
    - https://traefik.github.io/charts
    - https://kubernetes-sigs.github.io/node-feature-discovery/charts
    - https://intel.github.io/helm-charts
    - https://stakater.github.io/stakater-charts
    - https://charts.goauthentik.io
    - https://charts.rook.io/release
    - https://democratic-csi.github.io/charts
    - https://argoproj.github.io/argo-helm
    - https://bjw-s-labs.github.io/helm-charts
    - https://charts.external-secrets.io
    - https://kubernetes-sigs.github.io/external-dns/
    - https://prometheus-community.github.io/helm-charts
    - https://grafana.github.io/helm-charts
    - https://seaweedfs.github.io/seaweedfs/helm
    - https://oauth2-proxy.github.io/manifests
  destinations:
    - server: https://kubernetes.default.svc
      namespace: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
