---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 15m
  chart:
    spec:
      chart: cilium
      version: 1.17.2
      sourceRef:
        kind: HelmRepository
        name: cilium-charts
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    kubeProxyReplacement: true
    k8sServiceHost: "${KUBE_VIP_API_SERVER_IP}"
    k8sServicePort: 6443
    # See https://docs.cilium.io/en/latest/network/l2-announcements/#l2-announcements-l2-aware-lb-beta
    l2announcements:
      enabled: true
      # Values are high due to https://github.com/cilium/cilium/issues/26586
      leaseDuration: 300s
      leaseRenewDeadline: 60s
      leaseRetryPeriod: 10s
    # See https://docs.cilium.io/en/latest/network/l2-announcements/#sizing-client-rate-limit
    k8sClientRateLimit:
      qps: 5
      burst: 10
    hubble:
      enabled: true
      ui:
        enabled: true
      relay:
        enabled: true
      metrics:
        enabled:
          - dns
          - drop
          - tcp
          - flow
          - port-distribution
          - icmp
          - http
    operator:
      nodeSelector:
        node-role.kubernetes.io/master: "true"
      tolerations:
        - key: CriticalAddonsOnly
          operator: "Exists"
