---
apiVersion: v1
kind: Namespace
metadata:
  name: home-automation
  labels:
    # Required for zigbee2mqtt: needs privileged + hostPath for USB dongle
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
    pod-security.kubernetes.io/audit: privileged
