apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: vernemq-secrets
    namespace: home-automation
stringData:
    vmq.passwd: ENC[AES256_GCM,data:MQn7vp32HvyXa1dCugBwv39mQTEsNw==,iv:+XI+IYYmjqULw+PDK/hqlgzZs2zfl7md8evkuFFpLfE=,tag:1k/sSbN85TO65XKyavTh8A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-08-11T13:10:23Z"
    mac: ENC[AES256_GCM,data:mmGQjtWhGk22CNh5RiJ3dvVxFXiFrDPB+GH2JMmeXz1dtDcAZImvG/ymqrkcAdd2zJrferKJZpNGXGlIfqFHgPDtcekO8R0GyMvauvuiBCtd8MP6XyfliEglQVrF6po7dM9nepD92Tza3aOzp+8Gp249k3x5BPcLTJ05X3xmhjM=,iv:aIH7sgsmj1ANvqiYu63Wb2fvO3JojfZunT5VINFaz6I=,tag:cqZluu66JU20jmeoYp7Fiw==,type:str]
    pgp:
        - created_at: "2021-08-11T12:26:30Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA6+sJYMUUo72ARAAuvJgBzHs+Elfr+7QPQb17GjdwN1/rC8Y1VcndTO439rs
            oRkGwCKiM14Uf8OiD5Ek4G1T8UoLmaFgSpe3QO2Naf/wifsfXcQa4HhxyJ8m3nA4
            iZ4ZuvkfTHk/ZRVDniCxjXkrPfv1Zp1y1eHZOMhTsjM4JZ+E4WQDVJbzIgjlUEm8
            0Uyibnvzf+0SBkjnde7UV1Uf1UYhtpF0zwVwRNk36qc6lbm5/2vvzyxVWOQL0JNL
            wJiNeB07hhDZku6xBoYvhMkqCVfALYjnmybUcFAakv7zd3KOdyS12F5yA+VOIeCf
            oGN0ci59qpE5IRKmkp7x/jbpYqGACmadozw/98jtPL2scqxIfXl5850MVMLi//oT
            XtIZyrpJZ2aTSWiAq+Z88yoSf4gdDhT348tgywGuCh4nLAnD7xpe31z3bLMcL3sH
            R2HzSIR3UCRNFmE7yCPmTdognw3l7Tr6HIm6/pFT9PIMkbFwD9zMxihH1HBAsD7u
            xJ7My0cW0j0gF4LjQF48ZHYhm+pGmLUlzfZB/QE1T3BQq6nK1UUFisFaU3r95nZq
            DK+JnD8z674cEv3X+0BHlt46UEg1aAy8141oralW6S3k7g7cg5K7YvqBIda8ciKZ
            pj7zx9XVBJtIDgFUMxBGcHqlZ0F81lsyxzgMmKXlidpMbxPQ66EzrhrPlSSdNA/U
            aAEJAhUEBn7FFQ38KcVv53wMG9DJ9wNvn3Z2XMUlni+n+5WaKYv/dSqaeMZxXhas
            jcqw+b9g8e26NnRI/Ko0ET+G+j4WekEAdViP8abBFHoySsWGy+oM2hLh8uFUmK4m
            PKQ/cyTSyilP
            =+59n
            -----END PGP MESSAGE-----
          fp: B84ADBF2B1CBFB4B1D7812175BECD066ABE785D1
        - created_at: "2021-08-11T12:26:30Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAyoigsyNyDu0AQ/+MKinRwA4g86OWl/k8Neqt1+V1BunLePQJIz93x+RzFqg
            pEtg+pe6cQaQlS1UftwRCakSAX/dHgMFumU+F8UlYl5pdLw2XWZCa7BM8+vVP+zv
            8JfrqjL9PZ5sjCLEBBsDjE2yFhx29Uk90Swf1x7i+1WaurDLCI1kpqH3fcIv3OT1
            RkxhkqKcnvRymHtD9VpnjksNjulP0j+gko8efW0vHBslU7MMaxLrCaQsF70WjKZM
            LPhda5WBP926k24E2UHhlMckIsv68h2ILujsbLJ8ux/+xWyttZ6aEpNns66a0c1I
            /9aSG9gH1sTr5s/hhR1V6a9fnRavJUrDirLZcvvCwh4nsvRPpTLZHtuuahsOZoda
            FJFaPgILhgQ+sKwR3scswFyW4iTw2/+aqdd0rst2644352n3/qcuIDGtklDOimdy
            OTwWvNdM0FdSMllMy490ZAUx5mALMOjM3JcLEr67JYPiVACqtiUF/hV0XF46wnL/
            HhtHw83sfhQJZeg2xEYr9ORkbS6dquGL4vAdlEMqPlvn8urWgVDGzQ0QfA1aq1ye
            gWPDrfgfLs85lFZFV9RfAIxOpL9gwhJ+YjqMeIfw1kCRqNmVM8dd0eYnRJCCW2yN
            k4HJqgiqMFllDBRILaKjEwrpN4HdwC70Bu/8L40/KWrGNHXh6OAArYJomAxO1M3U
            aAEJAhVPESjIM26dLKP2Vv3de5KExqCipO7hU5qh6F8v0QOSXfSt8AMfO+XwF89X
            5HVT3ar/BaPIU5NEGUqfe6wMPwyuHdG8tixZB1Fco+4jtD/mBUUN8DIBzPrB0gf5
            bcIGn7zKek8X
            =Ua61
            -----END PGP MESSAGE-----
          fp: 3C78B9F2882CA975AD035A0F2B7AF27738EEB3FE
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
