---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: books-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
  storageClassName: longhorn-fast-replicated
---
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lazylibrarian-config
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn-fast-replicated