---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 5m
  chart:
    spec:
      chart: traefik
      version: 20.8.0
      sourceRef:
        kind: HelmRepository
        name: traefik-charts
        namespace: flux-system
  install:
    createNamespace: false
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    deployment:
      kind: Deployment
      replicas: 1
    service:
      enabled: true
      type: LoadBalancer
      spec:
        loadBalancerIP: "${TRAEFIK_LB}"
    ports:
      web:
        port: 80
        redirectTo: websecure
      websecure:
        port: 443
    # Enable both CRD and annotation methods of defining ingress
    providers:
      kubernetesCRD:
        enabled: true
        allowCrossNamespace: true
      kubernetesIngress:
        enabled: true
        # Needed, as otherwise ingresses don't get IPs automatically
        publishedService:
          enabled: true
    logs:
      general:
        level: DEBUG
      access:
        enabled: true
        fields:
          headers:
            defaultmode: keep
    additionalArguments:
      - "--entryPoints.websecure.forwardedHeaders.trustedIPs=10.0.0.0/8,192.168.0.0/16,173.245.48.0/20,103.21.244.0/22,103.22.200.0/22,103.31.4.0/22,141.101.64.0/18,108.162.192.0/18,190.93.240.0/20,188.114.96.0/20,197.234.240.0/22,198.41.128.0/17,162.158.0.0/15,172.64.0.0/13,131.0.72.0/22,104.16.0.0/13,104.24.0.0/14"
      - "--metrics.prometheus=true"
      - "--entryPoints.metrics.address=:9100"
      - "--metrics.prometheus.entryPoint=metrics"
    securityContext:
      capabilities:
        drop: [ALL]
        add: [NET_BIND_SERVICE]
      readOnlyRootFilesystem: true
      runAsGroup: 568
      runAsNonRoot: false
      runAsUser: 568
    podSecurityContext:
      fsGroup: 568
    resources:
      requests:
        cpu: 300m
        memory: 100Mi
      limits:
        memory: 500Mi
