apiVersion: v1
kind: Secret
metadata:
    name: minio-aws-secret
    namespace: longhorn-system
type: Opaque
data:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:cZwQBnQ6ZX6Hcg==,iv:/Obkg5G9dSL/glomy5QQ6SIIjnwtzWGPSDOrhaUsoMI=,tag:1YWHNabs4Px+ZZGjchrCBQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:yo5gSDuMBqPFQuovK4P6k9+OYCKbB2di4PiHD6q5NSgQsp4U37QPOw==,iv:Hn8vn7WBcrErSFSrXzZeH2o+5oxoF/Aqk3YrR5qntOY=,tag:FBqTDtCuUz7clZEeTK+eUg==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:OdNWSUnGRSAjRr751fgUX+QbRoeE4zvWq1CIRwUoGgbwDSDqtg==,iv:QJ5HFsOWdnwQ8K8u5y585htBXowWshEQkpt95v4q2YE=,tag:zx4JtJgJXpvdmlDAxuvuMA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-09-12T19:59:39Z"
    mac: ENC[AES256_GCM,data:/ijE1/RcZFt8FK93E8ZNKKZlqas9O2/v5IusBFodetwwH4jddwySJCrOFaSj20/uTuZOIdcDnloVudaTfSLb6FCa23GaQ6wXe5t7K5aBSuWjko8dMiHNnl/d4YPMsx29jEAfgMaNzgg3JejjIvw+NI5+KEGqQ78NOV5ao9Yfww4=,iv:YpiSH70PIEG9/KA1CTdVAdh3yMMufZImr6G0ufiNXdU=,tag:F4UmUP3UThBWn0tVVYCERw==,type:str]
    pgp:
        - created_at: "2021-09-12T19:59:38Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA6+sJYMUUo72AQ//UfapPZ5Mj/3pIG29WbveiWN3O0LjdtiYzMPSro63K1DT
            uSX9okuLkyL8aS2pfNszqGnEVJRLVaSLA3OgHGzvkx8GmM2MRKzEFOQON6gbjrNf
            U3fJh+Z6dEbXdehmL6/CensXqFGERerg2jUgvEX98ybwsalugg0PyMtN1hn1sfy/
            CB+KnADB/NAHKAHEb5aP21JqYqRV9qhGo756yXz4ZPA39HDx+rEjyvqx6+nnlrBT
            ldjnoHPqO14k82Jm735PNtNV1k6Y7NRzlnNZ7bFJndwTYnqmLVGb/5iLfKdAX0Qi
            yrpTp4HkQbGIkUsfzomIWY/KCDj06IpQdBfkbSr06+tqaeHmuyFXreVDEfLul54f
            vD0lJyQ9VF1cMqMYZTwIHSxEsttOzI+7xfz7rs/1B/n4qs8G5ZSxweAnvQz1jgyX
            mBs5oz3KQZI3tQFzpza0lJgIrq8j4OqBF4ZEY4+632kdGPepOJvRJhVCvibE9DyI
            6vfJBJeI6BueFPgxWb8M8ruQD1vwmafgjyBpGIs+x3BeuLQBNVW5FzmY6emmTEQU
            c9O7PDsKlm+tgf7gmorcVAGcKLxiA49fMD+INO3rpvT3g352IE/tTjM/C5ZbVs/0
            +aFuN1b1YRHhpffWb5QPuTmDVrLNwSzMjgtkZ6iF8SVJjE8TodZoPqROdt7+SlDU
            aAEJAhUowzncmZrzQ00G8jz+ITse9gPNv9lzghzIOTgsKIyQX1+Irw0DzIBjPtJ0
            /1vIZXCBVtQeq0y7iSQtihISdj8fgadr5hDxZqWYoRVKLyXQ8VKUh6KLJPhlHi/v
            z+uPZwI3UrGN
            =ruuw
            -----END PGP MESSAGE-----
          fp: B84ADBF2B1CBFB4B1D7812175BECD066ABE785D1
        - created_at: "2021-09-12T19:59:38Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAyoigsyNyDu0AQ/8DFhauXCYfI+WOyWX/ls5Hy+8AOy5y4kRCAmtXqVZzl/O
            EJR6sMrt1LvMxJv0UyDKnci5H9tf2Mm7aVWW6jEGIoa+o+/I32SsCHyqJMzO+NaX
            vo84HOZmsuMB7xdd7N5CEcXk48J5enlmXrcIQWyIayesbFE023lnGVSnxNWX1ywq
            JUTVGnC9mnE3zvvz8G6Cgja5MCR7yfCS4QtNsFpm5wmtl+lejyVNFZIBz2IgE5fC
            /81iO0BiGRvD1lnuuhE8bk9jKHtANefHwmeSR8UxMoZv6K5g5AWbq2I3cRu2m/HW
            mz/h6t9TtgcukIA96BXQnU44a5jJaPJHEpdv/ZGDSwbB8XOw4nY3dyELy5ef5gc8
            2xa4MZQElPBAj3d1B6IkvNgsUOj/svOBUPgcjD015rKo1HQn5vTAvEcP0PH4i2iZ
            P8qxulYPJNiJbrIfnkIgMkZWq1PR9eaWGNoMquS/MYU0Kwl8cyy+uVb+SvD3ABrz
            KnxNC5svwaTAttgXvgV1mfzswFHKT1ltouhpCP6VbngGo9Bu4FTToD5UMCWdiSPm
            qXdbKf8HgYQyKDnYJ2bnBa/rFkO/22sJjSkTBNY0j0DI0CVopTSv1M2JBBHp8IYP
            BlPNv30d4EiLCxPzl91IBJwCTZa8m2gmTBhpxM8iQlujRE212B9IsN2OiyPM/hnU
            aAEJAhXn5Q5+P+fSi/G0TmLAJH+ItMVyQfK2ajYBrKN0tlRxsEok/HI9Bj+S2VKy
            AFryszzUjqRsqgmM2nFH4sXPUnLwdVIcukVYIS9eKXKRntLghiZ0CNHsaOjdUeZV
            5kRK3vJKvkHg
            =1t6Q
            -----END PGP MESSAGE-----
          fp: 3C78B9F2882CA975AD035A0F2B7AF27738EEB3FE
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
