---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-fast
provisioner: driver.longhorn.io
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "480"
  diskSelector: "ssd"
  nodeSelector: "storage,fast"
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-fast-replicated
provisioner: driver.longhorn.io
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "480"
  diskSelector: "ssd"
  nodeSelector: "storage,fast"
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-slow
provisioner: driver.longhorn.io
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "480"
  diskSelector: "hdd"
  nodeSelector: "storage"
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-slow-replicated
provisioner: driver.longhorn.io
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "480"
  diskSelector: "hdd"
  nodeSelector: "storage"
---

