---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bazarr/ks.yaml
  - cast-sponsor-skip/ks.yaml
  # - deemix/ks.yaml
  - flare-bypasser/ks.yaml
  # - immich/ks.yaml
  - lidarr/ks.yaml
  - overseerr/ks.yaml
  - plex/ks.yaml
  - prowlarr/ks.yaml
  - qbittorrent/ks.yaml
  - radarr/ks.yaml
  - readarr/ks.yaml
  - sonarr/ks.yaml
  # - ytdl-sub/ks.yaml
  - namespace.yaml
