---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-charts
        namespace: flux-system
  interval: 30m
  values:
    image:
      repository: ghcr.io/onedr0p/plex
      tag: 1.32.8.7639-fb6452ebf
    env:
      TZ: "Europe/London"
    service:
      main:
        type: LoadBalancer
        externalTrafficPolicy: Cluster
        ports:
          http:
            port: 32400
    ingress:
      main:
        enabled: true
        annotations:
          # Automatically generate TLS certificate
          kubernetes.io/tls-acme: "true"
          # Let external-dns manage cloudflare DNS records
          external-dns/is-public: "true"
        hosts:
        - host: plex.${SECRET_DOMAIN}
          paths:
          - path: /
            pathType: Prefix
        tls:
        - secretName: plex-tls
          hosts:
          - plex.${SECRET_DOMAIN}
    persistence:
      config:
        enabled: true
        existingClaim: plex-config
      media:
        enabled: true
        mountPath: /data
        existingClaim: media-pvc
      transcode:
        enabled: true
        type: emptyDir
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: OnRootMismatch
      # Required for passthrough of /dev/dri devices. Fetched by running following on the host
      # cat /etc/group | grep "video\|render"
      # video:x:44:arsenikki
      # render:x:110:
      supplementalGroups:
        - 44
        - 110
    resources:
      requests:
        gpu.intel.com/i915: 1
        cpu: 1
        memory: 1024Mi
      limits:
        gpu.intel.com/i915: 1
        memory: 4096Mi
