---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: bazarr
  namespace: media
spec:
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-charts
        namespace: flux-system
  interval: 30m
  values:
    image:
      repository: ghcr.io/onedr0p/bazarr
      tag: 1.4.3
    env:
      TZ: "Europe/London"
    service:
      main:
        ports:
          http:
            port: 6767
    ingress:
      main:
        enabled: true
        ingressClassName: traefik
        annotations:
          # Automatically generate TLS certificate
          kubernetes.io/tls-acme: "true"
          # Use forward-auth middleware for authentication
          traefik.ingress.kubernetes.io/router.middlewares: "forward-auth@kubernetescrd"
        hosts:
          - host: bazarr.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: bazarr-tls
            hosts:
              - bazarr.${SECRET_DOMAIN}
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups: [10000]
    persistence:
      config:
        enabled: true
        existingClaim: bazarr-config
      media:
        enabled: true
        mountPath: /data
        existingClaim: media-pvc
    resources:
      requests:
        cpu: 10m
        memory: 64M
      limits:
        memory: 512M
