---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik-resources
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: kuberseni
  source:
    repoURL: https://github.com/Arsenikki/kuberseni-gitops
    targetRevision: main
    path: cluster/apps/authentik/resources
    directory:
      exclude: "values.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: authentik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
