---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarr
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: kuberseni
  sources:
    - repoURL: https://bjw-s-labs.github.io/helm-charts
      chart: app-template
      targetRevision: 5.0.1
      helm:
        valueFiles:
          - $values/cluster/apps/media/sonarr/values.yaml
    - repoURL: https://github.com/Arsenikki/kuberseni-gitops
      targetRevision: main
      ref: values
    - repoURL: https://github.com/Arsenikki/kuberseni-gitops
      targetRevision: main
      path: cluster/apps/media/sonarr
      directory:
        exclude: "values.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: media
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
