---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-feature-discovery
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: kuberseni
  sources:
    - repoURL: https://kubernetes-sigs.github.io/node-feature-discovery/charts
      chart: node-feature-discovery
      targetRevision: 0.19.0
      helm:
        valueFiles:
          - $values/cluster/apps/node-feature-discovery/values.yaml
    - repoURL: https://github.com/Arsenikki/kuberseni-gitops
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
