---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oauth2-proxy
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: kuberseni
  sources:
    - repoURL: https://oauth2-proxy.github.io/manifests
      chart: oauth2-proxy
      targetRevision: 7.12.8
      helm:
        valueFiles:
          - $values/cluster/apps/oauth2-proxy/values.yaml
    - repoURL: https://github.com/Arsenikki/kuberseni-gitops
      targetRevision: feat/talos
      ref: values
    - repoURL: https://github.com/Arsenikki/kuberseni-gitops
      targetRevision: feat/talos
      path: cluster/apps/oauth2-proxy
      directory:
        exclude: "values.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: oauth2-proxy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
