apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: cloudflared
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:pKK0SBP9bFL6u7o8JGziB6BN9k67DBQVUP7YGgmp,iv:auVTP5XzL8nSkbNdbKm6X8Ntd1pWQmm77SnbcrR6fpQ=,tag:VbRnEIhfQuiWaILV0NzYcw==,type:str]
    TUNNEL_TOKEN: ENC[AES256_GCM,data:+pAafUF/n4rBPZ9Me9ZFpckUgYs9MCInSSV+uuqUkB3R,iv:Kpc4+p+zWuC3V2uEP35IsYSM/iQ/zlCRxoBXixHd/M4=,tag:/eSy6CsqwlbWJLNAA2OWsw==,type:str]
    credentials.json: ENC[AES256_GCM,data:cdX1DwFcJ+3WFQJuseRkDE6b5f7MiDoCLH9DfYY2XvDWNdZgNG0G6e3kM4ozTrp1Mjm8oTWb31mNYUMuFve1qri2xrm4a3tE1OKRNd3an/L7M8+ZBSKlDQhQTo+KGWCeTigxvT4lr365NiMR08rpq4mdjyHb5rFTmGTDpQghzqOXb6VP+pkUUvk91JnVhN6ODFhRY8nSjUjTywa0RR0=,iv:wzMeynUxyUT1IQDuBb9/5KWbVMHJfSRZFKLzNhZTRzU=,tag:vV6ijeFbgJIykayyh7oyKw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17ax8w6axmjplnnf38t8qlqtz2uj2k685fwnl6uy6u8q2rwsjmd6qa6ddv9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDYzlVWldXWUZURkhWME9E
            WG95Nmk5ZXZYdHZEZlVyaVhRNFRHR0lHU2k0CjBzMVZrTjd4VVI3SXZPOC8ybkda
            d28vTHpGUDFRQnpQdjdqa3Q1bnZxWXMKLS0tIHpJdmZTYVlzRGpSa2MydUhINWRr
            VEwyZkFDTDUzWGR2TkRHb25CTTJrTHMKDAX5RtRL45NlCztu5IuU2Z2zWZm1qkBx
            y1l5ia1juSMsH1hhjOc4sXRf8cINvBYAGsxcSrOQo/FtzVPw8r3rMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-30T00:48:12Z"
    mac: ENC[AES256_GCM,data:uEdfOHVXq0p8TptqQ3ERcsmWInV+LWE0C17sojT/YeeH1myCkHikPGTMCArqowS9ld085amwdOvdTid0q5a8U0bANyCzjCxNKMyd3K+VgkTnK6Zc+36Ff7GN2qvnfzQ7zc7XxfFmSQVq2/GlV++n0lb1AyqXJnimmTqL/aQua4Q=,iv:KjMeWzbUqjva6pxZch8leEIUY65z++GkJjPpO24lfag=,tag:ODE6L2Wf+Aaj3uFTc7EEUw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
