---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: intel-gpu-plugin-app
  namespace: flux-system
spec:
  path: ./apps/intel-gpu-plugin/app
  prune: true
  sourceRef:
    kind: OCIRepository
    name: kuberseni-gitops-source
    namespace: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substitute: {}
    substituteFrom:
    - kind: ConfigMap
      name: cluster-settings
    - kind: Secret
      name: cluster-secrets
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: intel-gpu-plugin
      namespace: kube-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: intel-gpu-plugin-resources
  namespace: flux-system
spec:
  path: ./apps/intel-gpu-plugin/resources
  dependsOn:
    - name: intel-gpu-plugin-app
    - name: node-feature-discovery-app
  prune: true
  sourceRef:
    kind: OCIRepository
    name: kuberseni-gitops-source
    namespace: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substitute: {}
    substituteFrom:
    - kind: ConfigMap
      name: cluster-settings
    - kind: Secret
      name: cluster-secrets
  interval: 30m
  retryInterval: 1m
  timeout: 3m
