---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: core-cert-manager
  namespace: flux-system
spec:
  path: ./core/cert-manager/app
  prune: true
  sourceRef:
    kind: OCIRepository
    name: kuberseni-gitops-source
    namespace: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: cert-manager
      namespace: cert-manager
  interval: 30m
  retryInterval: 1m
  timeout: 3m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: core-cert-manager-issuers
  namespace: flux-system
spec:
  dependsOn:
    - name: core-cert-manager
  path: ./core/cert-manager/issuers
  prune: true
  sourceRef:
    kind: OCIRepository
    name: kuberseni-gitops-source
    namespace: flux-system
  interval: 30m
  retryInterval: 1m
  timeout: 3m