---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cert-manager-app
  namespace: flux-system
spec:
  path: ./core/cert-manager/app
  prune: true
  sourceRef:
    kind: OCIRepository
    name: kuberseni-gitops-source
    namespace: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substitute: {}
    substituteFrom:
    - kind: ConfigMap
      name: cluster-settings
    - kind: Secret
      name: cluster-secrets
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: cert-manager
      namespace: cert-manager
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cert-manager-resources
  namespace: flux-system
spec:
  path: ./core/cert-manager/resources
  dependsOn:
    - name: cert-manager-app
  prune: true
  sourceRef:
    kind: OCIRepository
    name: kuberseni-gitops-source
    namespace: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substitute: {}
    substituteFrom:
    - kind: ConfigMap
      name: cluster-settings
    - kind: Secret
      name: cluster-secrets
  interval: 30m
  retryInterval: 1m
  timeout: 3m