---
# OAuth2 Proxy GitHub credentials
# 1Password item: "kuberseni/oauth2-proxy" with fields: cookie_secret, client_id, client_secret
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: oauth2-proxy-secrets
  namespace: oauth2-proxy
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: oauth2-proxy-secrets
    creationPolicy: Owner
  data:
    - secretKey: cookie_secret
      remoteRef:
        key: "kuberseni/oauth2-proxy"
        property: cookie_secret
    - secretKey: client_id
      remoteRef:
        key: "kuberseni/oauth2-proxy"
        property: client_id
    - secretKey: client_secret
      remoteRef:
        key: "kuberseni/oauth2-proxy"
        property: client_secret
