---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: teleport-cluster
  namespace: teleport
spec:
  chart:
    spec:
      chart: teleport-cluster
      version: 16.4.7
      sourceRef:
        kind: HelmRepository
        name: teleport-charts
        namespace: flux-system
  interval: 30m
  values:
    chartMode: standalone
    log:
      level: DEBUG
    # NOTE: Kubernetes operator mode and the CRDs are still quite limited.
    # See https://github.com/gravitational/teleport/issues/29480 for details.
    operator:
      enabled: true
    clusterName: teleport.${SECRET_DOMAIN}
    acme: true
    acmeEmail: ${SECRET_AUTHELIA_EMAIL}
    authentication:
      type: local
    proxyListenerMode: multiplex
    podSecurityPolicy:
      enabled: false
    # persistence:
    #   enabled: true
    #   existingClaimName: teleport-cluster-data
