---
apiVersion: v1
kind: Secret
metadata:
  name: qbittorrent-helm-values
  namespace: media
stringData:
  values.yaml: |-
    addons:
      vpn:  
        configFile: |-
          [Interface]
          PrivateKey = ${PIA_PRIVATE_KEY}
          Address = 10.13.225.89
          DNS = 10.0.0.243,10.0.0.242
          PostUp = /config/up.sh %i
          PreDown = /config/down.sh %i
          [Peer]
          PublicKey = ${PIA_PUBLIC_KEY} 
          Endpoint = 188.126.89.79:1337
          AllowedIPs = 0.0.0.0/0
