---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: deemix-app
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-charts
        namespace: flux-system
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: registry.gitlab.com/bockiii/deemix-docker
              tag: 2022.12.14-r222.5d447b6035
              pullPolicy: IfNotPresent
            env:
              TZ: "Europe/London"
              PGUID: 568
              PGID: 568
              UMASK_SET: 022
              DEEMIX_SINGLE_USER: true
            resources:
              requests:
                cpu: 15m
                memory: 250M
              limits:
                memory: 1G
    service:
      main:
        ports:
          http:
            port: 6595
    ingress:
      main:
        enabled: true
        ingressClassName: traefik
        annotations:
          # Automatically generate TLS certificate
          kubernetes.io/tls-acme: "true"
        hosts:
          - host: &host deemix.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        existingClaim: deemix-config
      media:
        enabled: true
        globalMounts:
          - path: /downloads
            subPath: music
            readOnly: false
        existingClaim: media-pvc
