---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: forward-auth
  namespace: traefik
spec:
  forwardAuth:
    address: http://oauth2-proxy.auth.svc.cluster.local/oauth2/auth
    authResponseHeaders:
      - X-Auth-Request-User
      - Set-Cookie
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirect-sign-in
  namespace: traefik
spec:
  errors:
    status:
      - "401-403"
    service:
      name: oauth2-proxy
      namespace: auth
      port: 80
    query: "/oauth2/sign_in"
