---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: forward-auth
  namespace: traefik
spec:
  chain:
    middlewares:
      - name: forward-auth-errors
      - name: forward-auth-sign-in
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: oauth2-proxy-errors
  namespace: traefik
spec:
  errors:
    status:
      - "401-403"
    query: /oauth2/sign_in
    service:
      name: oauth2-proxy
      namespace: auth
      port: 80
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: oauth2-proxy-sign-in
  namespace: traefik
spec:
  forwardAuth:
    address: http://oauth2-proxy.auth.svc/oauth2/auth
    trustForwardHeader: true
    authResponseHeaders:
      - Authorization
      - Set-Cookie
      - X-Auth-User
      - X-Secret
