apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: oauth
spec:
  chain:
    middlewares:
      - name: traefik-https-redirect@kubernetescrd
      - name: oauth-errors
      - name: oauth-forward
---
# https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/overview/#configuring-for-use-with-the-traefik-v2-forwardauth-middleware
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: oauth-headers
  namespace: auth
spec:
  headers:
    sslRedirect: true
    stsSeconds: 315360000
    browserXssFilter: true
    contentTypeNosniff: true
    forceSTSHeader: true
    sslHost: ${SECRET_DOMAIN}
    stsIncludeSubdomains: true
    stsPreload: true
    frameDeny: true
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: oauth-errors
  namespace: auth
spec:
  errors:
    status:
      - "401-403"
    service:
      name: oauth2-proxy
      namespace: auth
      port: 80
    query: "/oauth2/sign_in?rd={url}"
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: oauth-forward
  namespace: auth
spec:
  forwardAuth:
    address: https://auth.${SECRET_DOMAIN}/oauth2/auth
    trustForwardHeader: true
