---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: casabot-credentials
  namespace: home-automation
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: casabot-credentials
    creationPolicy: Owner
  data:
    - secretKey: TELEGRAM_BOT_TOKEN
      remoteRef:
        key: "CasaBot (Telegram)"
        property: credential
