apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: server-upgrade-plan
  namespace: system-upgrade
spec:
  concurrency: 1
  cordon: true
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/control-plane
        operator: In
        values:
          - "true"
  tolerations:
    - key: CriticalAddonsOnly
      operator: "Exists"
  serviceAccountName: system-upgrade
  upgrade:
    image: rancher/k3s-upgrade
  version: v1.30.6+k3s1
