name: Lint
on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  pull_request:
permissions:
  contents: read
  pull-requests: write
jobs:
  yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yamllint
        uses: reviewdog/action-yamllint@b5f7217d8c815ae374d1d55840d5e569d82f01f0 # v1.22.0
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          yamllint_flags: '-c .github/yamllint.config.yaml ./cluster/'
