---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - networking.yaml
  - longhorn-system.yaml
  - home-automation.yaml
  - media.yaml
  - nextcloud.yaml
  - security.yaml
  - minio.yaml
  - observability.yaml
